<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php
    $bookingsData = json_decode($this->bookings, true);
    // var_dump($bookingsData);
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="margin-left:600px; font-weight:bold; font-size:25px;">INVOICES</div>
    <div style="margin-left:470px; font-weight:bold; font-size:25px;"></div>

    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:15px">
                                <th style="width:5%" class="text-center">ID</th>
                                <th style="width:20%; text-align:center" >Pickup DateTime</th>
                                <th style="width:20%; text-align:center" >Spoc Id/Name</th>
                                <th style="width:10%; text-align:center" >Tour Type</th>
                                <th style="width:35%; text-align:center" >Pickup Location</th>
                                <th style="width:10%; text-align:center" >Bill Amount</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){ ?>
                            <tr style="font-size:13px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] ?></td>
                                <td style="text-align:center"><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['pickup_datetime'])); ?></td>
                                <td style="text-align:center"><?php echo $bookingsData['response']['Bookings'][$i]['user_cid']."/". $bookingsData['response']['Bookings'][$i]['user_name'] ;?></td>
                                <td style="text-align:center">
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['tour_type'] == '1') { ?>
                                        Local
                                    <?php }else{ ?>
                                        Outstation
                                    <?php }?>
                                </td>
                                <td style="text-align:center"><?php echo substr($bookingsData['response']['Bookings'][$i]['pickup_location'], 0, 100); ?></td>
                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_invoice'] == '1'){ ?>
                                    <a id="viewinvoice_group_button" style="margin-left:23px;" class=" fa-trash" href="<?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){
                                        echo '/businessauthtwo/viewInvoiceRadio/'.$bookingsData['response']['Bookings'][$i]['invoice_id'];} else {
                                            echo '/businessauthtwo/viewInvoiceOutstation/'.$bookingsData['response']['Bookings'][$i]['invoice_id']; }?>">
                                        <?php echo "Rs.".round($bookingsData['response']['Bookings'][$i]['bill_amount'],2); ?>
                                    </a>
                                    <?php } ?>
                                </td>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {    

    $('#table_booking').DataTable({
        'paging': true,
        'aaSorting' : [],
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

});
</script>

