<style>
body{
    background-image: url("/css/landing_img/websiteimage.jpg");
}
</style>
<div class="form-box" id="login-box">
    <div class="header">Sign In - Approver Level 2</div>
    <form action="/postBusinessauthtwoLogin" method="post">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="Username"/>
            </div>
            <div class="form-group">
                <input type="password" name="password" class="form-control" placeholder="Password"/>
            </div>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Sign me in</button>  
              
            <p id="forgot_button"><a href="#">I forgot my password</a></p>      
        </div>
    </form>
</div>

<div class="form-box" id="forgot-box">
    <div class="header">Forgot Password</div>
    <form action="/postBusinessauthtwoForgot" method="post">
        <div class="body bg-gray">
            <div class="form-group">
                <input type="text" name="username" class="form-control" placeholder="Username/Email"/>
            </div>
        </div>
        <div class="footer">                                                               
            <button type="submit" class="btn bg-olive btn-block">Send New Password</button>
        </div>
    </form>
</div>

<?php
    if($this->mess)
    { ?>
        <div class="alert alert-danger alert-dismissable" style="width:400px;margin-left:480px;margin-top:20px">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b>Alert!</b> <?php echo $this->mess; ?>
        </div>
<?php } ?>

<?php
    if($this->mess_success)
    { ?>
        <div class="alert alert-success alert-dismissable" style="width:500px;margin-left:430px;margin-top:20px">
            <i class="fa fa-ban"></i>
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
            <b>Alert!</b> <?php echo $this->mess_success; ?>
        </div>
<?php } ?>


<script>
$(document).ready(function(){
    $('#forgot-box').hide();
    $('#forgot_button').click(function(){
        $('#login-box').hide();
        $('.alert').hide();
        $('#forgot-box').show();
    });
});
</script>
