<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'];  
            unset($_COOKIE['fail']);
            setcookie('fail', '', time() - 3600);
        ?>
    </div>
<?php } ?>

<?php 
    echo $this->headStyle()->appendStyle('/css/RegistrationForm.css');
    echo $this->inlineScript()->appendFile('/js/jquery.validate.min.js')->appendFile('/js/additional-methods.min.js');


    $profileData = json_decode($this->details, true);
    // var_dump($profileData);
?>

<?php echo $this->mess ;?>

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header" data-original-title="">
                <h2 class="box-title">Profile Details
                </h2>
            </div>
            <div class="box-content">
                <table class="table table-striped table-bordered bootstrap-datatable datatable responsive">
                    <tr>
                        <th style="width:350px">Employee Id</th>
                        <td><?php echo $profileData['response']['cid']; ?></td>
                    </tr>
                    <tr>
                        <th style="width:350px">Name</th>
                        <td><?php echo $profileData['response']['name']; ?></td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td><?php echo $profileData['response']['email']; ?></td>
                    </tr>
                    <tr>
                        <th>Company</th>
                        <td><?php echo $profileData['response']['corporate_name']; ?></td>
                    </tr>
                    <tr>
                        <th>Group</th>
                        <td><?php echo $profileData['response']['group_name']; ?></td>
                    </tr>
                    <tr>
                        <th>Sub Group</th>
                        <td><?php echo $profileData['response']['subgroup_name']; ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
<!--/span-->
</div><!--/row-->

<div class="row">
    <div class="box col-md-12">
        <div class="box-inner">
            <div class="box-header" data-original-title="">
                <h4 style="font-weight:bold"></i> Change Password</h4>
            </div>
            <div class="box-content">
                        <form id="add-operator-form" role="form" action="/businessauthone/changepassword" method="POST">
    
                            <div class="form-group">
                                <label for="driver_name">Current Password</label>
                                <input type="password" class="form-control" name="current_password" id="current_password" placeholder="Current Password" required>
                            </div>

                            <div class="form-group">
                                <label for="driver_name">New Password</label>
                                <input type="password" class="form-control" name="new_password" id="new_password" placeholder="New Password" required>
                            </div>

                            <div class="form-group">
                                <label for="driver_name">Confirm New Password</label>
                                <input type="password" class="form-control" name="confirm_new_password" id="confirm_new_password" placeholder="Re-Type New Password" required>
                            </div>

                            <button type="submit" class="btn btn-default"> CHANGE </button>

                        </form>
            </div>
        </div>
    </div>
    <!--/span-->

</div><!--/row-->


















