<div id="add_group_form" class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Select Reason for Cancelation/Rejection</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/authonebooking/reject/<?php echo $this->booking_id ?>" method="POST" role="form">
        <div class="box-body">

            <div class="control-group">
                <label class="control-label" for="selectError">Reason</label>
                    <div class="controls">
                        <select name="reason_cancel" id="reason_cancel" data-rel="chosen" required>
                            <option selected value="">Select</option>
                            <option value="Booking Rejected Completely">Booking Rejected Completely</option>
                            <option value="Booking rejected due to lack of clarification. Please make a new booking with proper information">Booking rejected due to lack of clarification. Please make a new booking with proper information</option>
                        </select>
                    </div>
                </label>
            </div><br>

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            
        </div>
    </form>
</div>