<?php
$invoiceData = json_decode($this->invoice, true);
?>

<style>
div.img {
    margin: 5px;
    border: 1px solid #ccc;
    float: left;
    width: 180px;
}

div.img:hover {
    border: 1px solid #777;
}

div.img img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text-align: center;
}
</style>

<?php if($invoiceData['response']['Invoice']['duty_slip'] == ''  ) {?>
<?php } else { ?>
    <div class="img" style="margin-left:450px">
        <a target="_blank" href="<?php echo $invoiceData['response']['Invoice']['duty_slip'] ; ?>">
            <img src="<?php echo $invoiceData['response']['Invoice']['duty_slip'] ; ?>">
        </a>
        <div class="desc">Payin-Slip</div>
    </div>
<?php }?>

<div class="row">
    <div class="box col-md-12">
    <!-- <div class="box-inner"> -->
    <!-- <div class="box-header well" data-original-title=""> -->
        <h2 style="margin-left:340px"><i class="glyphicon glyphicon-list-alt"></i> Invoice : <a href="/businessauthone/viewBooking/<?php echo $invoiceData['response']['Invoice']['booking_id'] ?>"> <?php echo $invoiceData['response']['Invoice']['reference_no']; ?></a></h2>
    <!-- </div> -->

    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive" style="width:700px; margin-left:200px">

    <!--<tr>
        <th>Car Model</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxi_model_name']; ?></td>
    </tr>

    <tr>
        <th>Total Hous Done</th>
        <td><?php echo $invoiceData['response']['Invoice']['hours_done']; ?></td>
    </tr>

    <tr>
        <th>Extra Hours</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_hours']; ?></td>
    </tr>

    <tr style="border:2px solid black">
        <th>Extra Hours Charge (@Rs<?php echo $invoiceData['response']['Invoice']['hour_rate'] ?>/Hour)</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_hours_charge']; ?></td>
    </tr>

    <tr>
        <th>Total Kms Done</th>
        <td><?php echo $invoiceData['response']['Invoice']['kms_done']; ?></td>
    </tr>

    <tr>
        <th>Extra Kms</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_kms']; ?></td>
    </tr>

    <tr style="border-top:2px solid black ; border-left:2px solid black; border-right:2px solid black">
        <th>Extra Kms Charge (@Rs<?php echo $invoiceData['response']['Invoice']['km_rate'] ?>/Km)</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_kms_charge']; ?></td>
    </tr>

    <tr style="border-left:2px solid black; border-right:2px solid black;border-bottom:2px solid black">
        <th>Package Base Rate</th>
        <td><?php echo $invoiceData['response']['Invoice']['base_rate']; ?></td>
    </tr>

    <tr bgcolor="#ffffcc">
        <th>Total (Excluding Tax)</th>
        <td><?php echo $invoiceData['response']['Invoice']['total_ex_tax']; ?></td>
    </tr>

    <tr style="border:2px solid black;">
        <th>Tax (@<?php echo $invoiceData['response']['Invoice']['tax_rate']; ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['tax']; ?></td>
    </tr>

    <tr bgcolor="#FFD929">
        <th>Total (Rs)</th>
        <td><?php echo $invoiceData['response']['Invoice']['total']; ?></td>
    </tr>

    <tr style="border-left:2px solid black; border-right:2px solid black; border-top:2px solid black;">
        <th>Taxivaxi Convenience Charge (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_rate'] ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxivaxi_charge']; ?></td>
    </tr>

    <tr style="border-left:2px solid black; border-right:2px solid black; border-bottom:2px solid black;">
        <th>Taxivaxi Tax (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_rate'] ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_charge']; ?></td>
    </tr>

    <tr bgcolor="#FFD929">
        <th>Sub Total (Rs)</th>
        <td><?php echo $invoiceData['response']['Invoice']['sub_total']; ?></td>
    </tr>-->
    
     <tr>
        <th>Total (Rs)</th>
        <td><?php echo $invoiceData['response']['Invoice']['total']; ?></td>
    </tr>

    <tr>
        <th>Taxivaxi Management Fee (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_rate'] ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxivaxi_charge']; ?></td>
    </tr>

    <tr>
        <th>Service Tax (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_rate'] ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_charge']; ?></td>
    </tr>

    <tr bgcolor="#FFD929">
        <th>Sub Total (Rs)</th>
        <td><?php echo $invoiceData['response']['Invoice']['sub_total']; ?></td>
    </tr>


   
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->
<script>
$(document).ready(
    function(){
        $('input:file').change(
            function(){
                if ($(this).val()) {
                    $('input:submit').attr('disabled',false);
                    // or, as has been pointed out elsewhere:
                    // $('input:submit').removeAttr('disabled'); 
                } 
            }
            );
    });
</script>