<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>admin for Business | Business Admin Dashboard</title>
        <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>

        <?php echo $this->inlineScript(); ?> 

        <!-- bootstrap 3.0.2 -->
        <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
        <!-- font Awesome -->
        <link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
        <!-- Ionicons -->
        <link href="/css/ionicons.min.css" rel="stylesheet" type="text/css" />
        <!-- jvectormap -->
        <link href="/css/jvectormap/jquery-jvectormap-1.2.2.css" rel="stylesheet" type="text/css" />
        <!-- fullCalendar -->
        <link href="/css/fullcalendar/fullcalendar.css" rel="stylesheet" type="text/css" />
        <!-- Daterange picker -->
        <link href="/css/daterangepicker/daterangepicker-bs3.css" rel="stylesheet" type="text/css" />
        <!-- bootstrap wysihtml5 - text editor -->
        <link href="/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.min.css" rel="stylesheet" type="text/css" />
        <!-- Theme style -->
        <link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />

        <link href="/css/dialog.css" rel="stylesheet" type="text/css" />

        <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
        <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
        <!--[if lt IE 9]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
        <![endif]-->

        <!-- <link href="/editable_library/libs/bootstrap/css/bootstrap.css" rel="stylesheet"> -->
        <link href="/editable_library/bootstrap-editable/css/bootstrap-editable.css" rel="stylesheet">

        <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/t/dt/dt-1.10.11/datatables.min.css"/>

        <!-- jQuery 2.0.2 -->
        <script src="/js/jquery.min.js" type="text/javascript"></script>
        <!-- jQuery UI 1.10.3 -->
        <script src="/js/jquery-ui-1.10.3.min.js" type="text/javascript"></script>
        <!-- Bootstrap -->
        <script src="/js/bootstrap.min.js" type="text/javascript"></script>

        <script src="/js/dialog.js" type="text/javascript"></script>

		<!--Start of Zopim Live Chat Script-->
<script type="text/javascript">
window.$zopim||(function(d,s){var z=$zopim=function(c){z._.push(c)},$=z.s=
d.createElement(s),e=d.getElementsByTagName(s)[0];z.set=function(o){z.set.
_.push(o)};z._=[];z.set._=[];$.async=!0;$.setAttribute("charset","utf-8");
$.src="//v2.zopim.com/?3lMEAL7wSlwmRTl4msDQszIsX3eg6oJ3";z.t=+new Date;$.
type="text/javascript";e.parentNode.insertBefore($,e)})(document,"script");
</script>
<!--End of Zopim Live Chat Script-->
    </head>
    <body class="skin-blue">
        <!-- header logo: style can be found in header.less -->

        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel"
         aria-hidden="true">

        <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">×</button>
                        <h3>Confirm This Action</h3>
                    </div>
                    <div class="modal-body" id="modal-body">
                        Here settings can be configured...
                    </div>
                    <div class="modal-footer">
                        <a href="#"  class="btn btn-primary" data-dismiss="modal">Close</a>
                        <a class="dialogboxfoot" id="dialogboxfoot"></a>
                    </div>
                </div>
            </div>
        </div>
        
        <header class="header">
            <a href="/businessadmin/home" class="logo" style="width:100px;">
                <!-- Add the class icon to your logo image or logo icon to add the margining -->
                admin
            </a>
            <!-- Header Navbar: style can be found in header.less -->
            <nav class="navbar navbar-static-top" role="navigation" style="margin-left:100px">
                <?php if (isset($_COOKIE['access_token_business_admin'])){ if (isset($_COOKIE['business_admin'])){?>
                <!-- Sidebar toggle button-->
                
                <div class="navbar-left" style="font-size:12px">
                    <ul class="nav navbar-nav">
                        <!--<li class="active">
                            <a href="/businessadmin/home">
                                <i class="fa fa-dashboard"></i> <span>Dashboard</span>
                            </a>
                        </li>-->
                        <?php if($_COOKIE['has_assessment_codes'] == '1') { ?>
    						<li>
                                <a href="/businessadmin/assessment-codes">
                                    <i class="fa fa-laptop"></i>
                                    <span>Codes</span>
                                </a>
                            </li>
                        <?php } ?>
                        <?php if($_COOKIE['has_auth_level'] == '1') {?>
                            <li>
                                <a href="/businessadmin/groups">
                                    <i class="fa fa-bar-chart-o"></i>
                                    <span>Groups</span>
                                </a>
                            </li>
                            <li>
                                <a href="/businessadmin/subgroups">
                                    <i class="fa fa-laptop"></i>
                                    <span>Sub Groups</span>
                                </a>
                            </li>
                        <?php }?>
                        <li>
                            <a href="/businessadmin/spocs">
                                <i class="fa fa-edit"></i> <span>Spocs</span>
                            </a>
                        </li>
                        <li>
                            <a href="/businessadmin/employees">
                                <i class="fa fa-edit"></i> <span>Employees</span>
                            </a>
                        </li>
                        <?php if($_COOKIE['is_radio'] == '1' || $_COOKIE['is_local'] == '1' || $_COOKIE['is_outstation'] == '1') { ?>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Taxi Bookings<span class="caret"></span></a>
                              <ul class="dropdown-menu">
                                <li><a href="/businessadmin/bookings/1">Active Bookings(Unassigned)</a></li>
                                <li><a href="/businessadmin/bookings/2">Active Bookings(Assigned)</a></li>
                                <li><a href="/businessadmin/bookings/3">Archived Bookings</a></li>
                                <li><a href="/businessadmin/bookings/4">Cancelled/Rejected Bookings</a></li>
                              </ul>
                            </li>
                        <?php } ?>
                        <?php if($_COOKIE['is_bus'] == '1') { ?>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bus Bookings<span class="caret"></span></a>
                              <ul class="dropdown-menu">
                                <li><a href="/businessadmin/busbookings/1">Active Bookings(Unassigned)</a></li>
                                <li><a href="/businessadmin/busbookings/2">Active Bookings(Assigned)</a></li>
                                <li><a href="/businessadmin/busbookings/3">Archived Bookings</a></li>
                                <li><a href="/businessadmin/busbookings/4">Cancelled/Rejected Bookings</a></li>
                              </ul>
                            </li>
                        <?php } ?>
                        <?php if($_COOKIE['is_radio'] == '1' || $_COOKIE['is_local'] == '1' || $_COOKIE['is_outstation'] == '1') { ?>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Taxi Invoices<span class="caret"></span></a>
                              <ul class="dropdown-menu">
                                <li><a href="/businessadmin/invoices/1">New Invoices: Unbilled</a></li>
                                <li><a href="/businessadmin/invoices/2">Invoices : Cleared for Billing by Spoc</a></li>
                                <li><a href="/businessadmin/invoices/6">Invoices : Cleared for Billing</a></li>
                                <!--<li><a href="/businessadmin/invoices/7">Invoices: Correction/ comments needed</a></li>-->
                                <li><a href="/businessadmin/invoices/4">Billed Invoices: Unpaid</a></li>
                                <li><a href="/businessadmin/invoices/5">Paid Invoices</a></li>
                              </ul>
                            </li>
                        <?php } ?>
                        <?php if($_COOKIE['is_bus'] == '1') { ?>
                            <li class="dropdown">
                              <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bus Invoices<span class="caret"></span></a>
                              <ul class="dropdown-menu">
                                <li><a href="/businessadmin/businvoices/1">New Invoices: Unbilled</a></li>
                                <li><a href="/businessadmin/businvoices/2">Invoices : Cleared for Billing by Spoc</a></li>
                                <li><a href="/businessadmin/businvoices/6">Invoices : Cleared for Billing</a></li>
                                <!--<li><a href="/businessadmin/businvoices/7">Invoices: Correction/ comments needed</a></li>-->
                                <li><a href="/businessadmin/businvoices/4">Billed Invoices: Unpaid</a></li>
                                <li><a href="/businessadmin/businvoices/5">Paid Invoices</a></li>
                              </ul>
                            </li>
                        <?php } ?>
                        <li class="dropdown">
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Bills<span class="caret"></span></a>
                          <ul class="dropdown-menu">
                            <li><a href="/businessadmin/bills/1">Unpaid-Bills</a></li>
                            <li><a href="/businessadmin/bills/2">Paid Bills</a></li>
                          </ul>
                        </li>
                    </ul>
                </div>
                <div class="navbar-right">
                    <ul class="nav navbar-nav">
                        <!-- User Account: style can be found in dropdown.less -->
                        <li class="dropdown user user-menu">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <i class="glyphicon glyphicon-user"></i>
                                <span><?php echo $_COOKIE['business_name'];?></i></span>
                                <span><?php echo "(".$_COOKIE['business_email'] . ")";?> <i class="caret"></i></span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="/businessadmin/profile" class="btn btn-default btn-flat">Profile</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="/businessadminLogout" class="btn btn-default btn-flat">Sign out</a>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
                <?php  }} ?>
            </nav>
        </header>
        <?php if (isset($_COOKIE['access_token_business_admin'])){ if (isset($_COOKIE['business_admin'])){?>
        
        <?php }}  ?>
                <div style="margin:20px">
                    <?php echo $this->content; ?>
                </div>

        <?php if (isset($_COOKIE['access_token_business_admin'])){ if (isset($_COOKIE['business_admin'])){ ?>
        
        <?php }} ?>

        <!-- add new calendar event modal -->

        
        <!-- Sparkline -->
        <script src="/js/plugins/sparkline/jquery.sparkline.min.js" type="text/javascript"></script>
        <!-- jvectormap -->
        <script src="/js/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js" type="text/javascript"></script>
        <script src="/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js" type="text/javascript"></script>
        <!-- fullCalendar -->
        <script src="/js/plugins/fullcalendar/fullcalendar.min.js" type="text/javascript"></script>
        <!-- jQuery Knob Chart -->
        <script src="/js/plugins/jqueryKnob/jquery.knob.js" type="text/javascript"></script>
        <!-- daterangepicker -->
        <script src="/js/plugins/daterangepicker/daterangepicker.js" type="text/javascript"></script>
        <!-- Bootstrap WYSIHTML5 -->
        <script src="/js/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js" type="text/javascript"></script>
        <!-- iCheck -->
        <script src="/js/plugins/iCheck/icheck.min.js" type="text/javascript"></script>

        <!-- AdminLTE App -->
        <script src="/js/AdminLTE/app.js" type="text/javascript"></script>  

        <script src="/editable_library/bootstrap-editable/js/bootstrap-editable.min.js"></script>      

        <script type="text/javascript" src="https://cdn.datatables.net/t/dt/dt-1.10.11/datatables.min.js"></script>

    </body>
</html>