<!DOCTYPE html>
<html lang="en">

<head>
    <link rel="shortcut icon" type="image/x-icon" href="/img/TaxiVaxi_Logo.png" />
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>TaxiVaxi Corporate</title>

    <!-- Bootstrap Core CSS -->
    <link rel="stylesheet" href="/css/landing_page/bootstrap.min.css" type="text/css">

    <!-- Custom Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic,900,900italic' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="/font-awesome/landing_page/css/font-awesome.min.css" type="text/css">

    <!-- Plugin CSS -->
    <link rel="stylesheet" href="/css/landing_page/animate.min.css" type="text/css">

    <!-- Custom CSS -->
    <link rel="stylesheet" href="/css/landing_page/creative.css" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body id="page-top">

    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand page-scroll" href="#" style="color:black">TAXIVAXI</a>
                <!-- <img src="/img/TaxiVaxi_Logo.png" style="max-width:100px"> -->
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a class="page-scroll" href="#">24x7 Helpline : +91 9990045853</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <header>
        <div class="header-content">
            <div class="header-content-inner">
                <h1 style="color:black">Your Favorite Source of Travel</h1>
                <hr>
                <p style="color:white; text-shadow: black 0.1em 0.1em 0.2em"><b>TaxiVaxi corporate is India’s first corporate solution which allows cash less and paperless travel for corporate travellers and allow booking Radio Taxi and Outstation taxi on one platform.</b></p>
                <ul style="list-style-type:none">
                    <li style="float:left">
                        <a href="/admin/login" class="btn btn-primary btn-xl page-scroll">Admin Login</a>
                    </li>
                    <li style="float:left; margin-left:50px">
                        <a href="/authtwo/login" class="btn btn-primary btn-xl page-scroll">Approver 2 Login</a>
                    </li>
                    <li style="float:left; margin-left:50px">
                        <a href="/authone/login" class="btn btn-primary btn-xl page-scroll">Approver 1 Login</a>
                    </li>
                    <li style="float:left; margin-left:50px">
                        <a href="/spoc/login" class="btn btn-primary btn-xl page-scroll">Spoc Login</a>
                    </li>
                </ul>
                
            </div>
        </div>
    </header>

    

    <!-- jQuery -->
    <script src="/js/landing_page/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/js/landing_page/bootstrap.min.js"></script>

    <!-- Plugin JavaScript -->
    <script src="/js/landing_page/jquery.easing.min.js"></script>
    <script src="/js/landing_page/jquery.fittext.js"></script>
    <script src="/js/landing_page/wow.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="/js/landing_page/creative.js"></script>

</body>

</html>
