<?php
$invoiceData = json_decode($this->invoice, true);
//var_dump($invoiceData); die;
?>
<style>
div.img {
    margin: 5px;
    border: 1px solid #ccc;
    float: left;
    width: 180px;
}

div.img:hover {
    border: 1px solid #777;
}

div.img img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text-align: center;
}
</style>

<?php //if($invoiceData['response']['Invoice']['ticket'] == ''  ) {?>
    <!--<form name="edit_form" action="/businesstaxivaxi/addBusTicket" method="POST" enctype="multipart/form-data">
                    <div class="form-group" style="float:left; margin-left:350px">
                        Browse Bus Ticket:
                        <input class="btn btn-default" type="file" name="image" id="imgInp">
                        <input type="hidden" name="invoice_id" value="<?php echo $invoiceData['response']['Invoice']['id'] ; ?>">
                    </div>
                    <div class="form-group" style="float:right; margin-right:350px; margin-top:22px">
                        <input value="Upload Bus Ticket(JPG, JPEG, PNG)" type="submit" class="btn btn-info btn-sm" id="save_button" disabled>
                    </div>
                </form>-->
<?php //} else { ?>
    <div class="img" style="margin-left:450px">
        <a target="_blank" href="<?php echo $invoiceData['response']['Invoice']['ticket'] ; ?>">
            <img src="<?php echo $invoiceData['response']['Invoice']['ticket'] ; ?>">
        </a>
        <div class="desc">Bus Ticket</div>
    </div>
<?php //}?>

<div class="row">
    <div class="box col-md-12">
    <!-- <div class="box-inner"> -->
    <!-- <div class="box-header well" data-original-title=""> -->
        <h2 style="margin-left:340px"><i class="glyphicon glyphicon-list-alt"></i> Invoice : <a href="/businessadmin/viewBusBooking/<?php echo $invoiceData['response']['Invoice']['booking_id'] ?>"> <?php echo $invoiceData['response']['Invoice']['reference_no']; ?></a></h2>
    <!-- </div> -->

	<table class="table table-striped table-bordered bootstrap-datatable datatable responsive" style="width:700px; margin-left:200px; font-size: 12px">

	<tr>
        <th>Operator Name</th>
        <td><?php echo $invoiceData['response']['Invoice']['operator_name']; ?></td>
    </tr>

    <tr>
        <th>Operator Contact</th>
        <td><?php echo $invoiceData['response']['Invoice']['operator_contact']; ?></td>
    </tr>

    <tr>
        <th>Pickup Date</th>
        <td><?php echo date("d M Y", strtotime($invoiceData['response']['Invoice']['pickup_datetime_taxivaxi'])); ?></td>
    </tr>

    <!-- <tr style="border: solid 2px #ff0000">
        <th>Ticket Price</th>
        <td><?php echo $invoiceData['response']['Invoice']['total']; ?></td>
    </tr>

    <tr>
        <th>Management Fee</th>
        <td><?php echo "Rs. ".$invoiceData['response']['Invoice']['taxivaxi_charge']; ?></td>
    </tr>

    <tr>
        <th>Service Tax (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_rate'] ?>%)</th>
        <td><?php echo "Rs. ".$invoiceData['response']['Invoice']['taxivaxi_tax_charge']; ?></td>
    </tr>
	<tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
    </tr>
    <tr bgcolor="#1fc516">
        <th>Total (Rs)</th>
        <td><?php echo $invoiceData['response']['Invoice']['sub_total']; ?></td>
    </tr> -->

   
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->
<script>
$(document).ready(
    function(){
        $('input:file').change(
            function(){
                if ($(this).val()) {
                    $('input:submit').attr('disabled',false);
                    // or, as has been pointed out elsewhere:
                    // $('input:submit').removeAttr('disabled'); 
                } 
            }
            );
    });
</script>