<?php 
    echo $this->headStyle()->appendStyle('/css/RegistrationForm.css');
    echo $this->inlineScript()->appendFile('/js/jquery.validate.min.js')->appendFile('/js/additional-methods.min.js');


    $bookingData = json_decode($this->booking, true);
?>
<script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?libraries=places"></script>
<?php if(isset($_COOKIE['error'])) { ?>

        <div class="box-content alerts" style="width:400px; margin:0 auto;">
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">&times;</button>
                    <strong><?php echo $_COOKIE['error'] ?></strong>
                </div>
            </div>


    <?php } ?>

<?php 
    //echo $this->headStyle()->appendStyle('/css/RegistrationForm.css');
    //echo $this->inlineScript()->appendFile('/js/jquery.validate.min.js')->appendFile('/js/additional-methods.min.js');


    $companiesData = json_decode($this->booking, true);
?>
<section class="content" style="font-size: 12px">
<form id="add-operator-form" action="/postAddAssignBusBooking" method="POST" enctype="multipart/form-data">
<div class="row">
    <div class="col-md-3">
        <div class="box">
            <div class="box-header" data-original-title="">
                <h2 class="box-title">Booking Details: <?php echo $companiesData['response']['BookingDetail']['reference_no']; ?>
                </h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Booking Reference No</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['reference_no']; ?></td>
                    </tr>
                    <tr>
                        <th>Tour Type</th>
                        <td>Bus</td>
                    </tr>
                    <tr>
                        <th>From City</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['pickup_city']; ?></td>
                    </tr>
                    <tr>
                        <th>To City</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['drop_city']; ?></td>
                    </tr>
                     <tr>
                        <th>Booking Date</th>
                        <td><?php echo date("d M Y - h:i a", strtotime($companiesData['response']['BookingDetail']['created'])); ?></td>
                    </tr>
                    <tr>
                        <th>Journey DateTime (Requested)</th>
                        <td><?php if($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == 3) {echo date("d M Y - h:i a", strtotime($companiesData['response']['BookingDetail']['pickup_datetime_taxivaxi']));} else { echo date("d M Y - h:i a", strtotime(explode("::",$companiesData['response']['BookingDetail']['time_range'])[1])); ?><br>To<br>
                                    <?php echo date("d M Y - h:i a", strtotime(explode("::",$companiesData['response']['BookingDetail']['time_range'])[0])); }?>
                        </td>
                    </tr>
                    
                    <tr>
                        <th>Bus Type (Priorities)</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['bus_type_priority_1']; ?><br><?php echo $companiesData['response']['BookingDetail']['bus_type_priority_2']; ?><br>
                                    <?php echo $companiesData['response']['BookingDetail']['bus_type_priority_3'];?>
                        </td>
                    </tr>
					
                    <tr>
                        <th>Status</th>
                        <td><?php if($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '0'){ ?><span class="label label-warning">Pending</span>
                            <?php }elseif ($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '1') { ?><span class="label label-primary">Accepted</span>
                            <?php }elseif ($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '2') { ?><span class="label label-danger">Rejected</span>
                            <?php }else{?><span class="label label-success">Assigned</span>
                            <?php }?>
                        </td>
                    </tr>
                    
                    <tr>
                        <th>Assessment Code</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['assessment_code']; ?></td>
                    </tr>
                    <tr>
                        <th>Reason for Booking</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['reason_of_booking']; ?></td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
 <div class="col-md-3">
			
    <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title"> Bus Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <tr>
        <th>Ticket Number</th>
        <td> <div class="form-group" style="clear:left;">
                                
        <input type="text" class="form-control" name="ticket_number" id="ticket_number" placeholder="Ticket Number" value="<?php echo $companiesData['response']['BookingDetail']['ticket_number']; ?>" required>
    </div></td>
    </tr>

    <tr>
        <th>PNR Number</th>
        <td> <div class="form-group" style="clear:left;">
                                
        <input type="text" class="form-control" name="pnr_number" id="pnr_number" placeholder="PNR Number" value="<?php echo $companiesData['response']['BookingDetail']['pnr_number']; ?>" required>
    </div></td>
    </tr>

    <tr>
        <th>Bus Type</th>
        <td><div class="form-group" style="clear:left;">
                                
        <input type="text" class="form-control" name="bus_type_allocated" id="bus_type_allocated" placeholder="Bus Type" value="<?php echo $bookingData['response']['BookingDetail']['bus_type_priority_1']; ?>" required>
    </div></td>
    </tr>

    <tr>
        <th>Operator Name</th>
        <td><div class="form-group" style="clear:left;">
                                
        <input type="text" class="form-control" name="operator_name" id="operator_name" placeholder="Operator Name" value="<?php echo $companiesData['response']['BookingDetail']['operator_name']; ?>" required>
    </div></td>
    </tr>
    
    <tr>
        <th>Operator Contact</th>
        <td><div class="form-group" style="clear:left;">
                              
        <input type="text" class="form-control" name="operator_contact" id="operator_contact" placeholder="Operator Contact" value="<?php echo $companiesData['response']['BookingDetail']['operator_contact']; ?>" required>
    </div></td>
    </tr>

    <tr>
        <th>Seat Number</th>
        <td><div class="form-group" style="clear:left;">
            <input type="text" class="form-control" name="seat_number" id="seat_number" placeholder="Seat Number" value="<?php echo $companiesData['response']['BookingDetail']['seat_number']; ?>" required>
        </div></td>
    </tr>
   
    </table>
    </div>

    <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title">Spoc Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
 
    <tr>
        <th>Spoc Name</th>
        <td><?php echo $companiesData['response']['BookingDetail']['user_name'] ?></td>
    </tr>
    <tr>
        <th>Spoc Contact Email</th>
        <td><?php echo $companiesData['response']['BookingDetail']['user_email'] ?></td>
    </tr>

    <tr>
        <th>Spoc Contact No</th>
        <td><?php echo $companiesData['response']['BookingDetail']['user_contact'] ?></td>
    </tr>
   
    </table>
    </div>
    </div>

    </div>
    
        </div>
 <div class="col-md-3">

    <div class="box">
            <div class="box-header" data-original-title="">
                <h2 class="box-title"> Billing Details</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped">
                        <input type="hidden" name="booking_id" value="<?php echo $this->booking_id; ?>"/>
                        <div class="form-group">
                            <label for="pickup_location">Ticket Price (Including Tax)</label>
                            <input type="number" class="form-control" name="total" id="total" placeholder="Total (With Tax)" 
                            style="border:1px solid green" step="0.01">
                        </div>                  
                        <div class="form-group">
                            <label for="pickup_location">Management Fee</label>
                            <input type="number" class="form-control" name="taxivaxi_charge" id="taxivaxi_charge" value="100" readonly required step="0.01">
                        </div>
                        <div class="form-group">
                            <label for="pickup_location">Service Tax Rate</label>
                            <input type="number" class="form-control" name="taxivaxi_tax_rate" id="taxivaxi_tax_rate" placeholder="Tax" value="14.5"  step="0.01">
                        </div>
                        <div class="form-group">
                            <label for="pickup_location">Service Tax</label>
                            <input type="number" class="form-control" name="taxivaxi_tax_charge" id="taxivaxi_tax_charge" placeholder="Taxivaxi Tax" readonly  step="0.01">
                        </div>
                        <div class="form-group">
                            <label for="pickup_location">Sub Total = Total + Management Fee + Service Tax</label>
                            <input type="number" class="form-control" name="sub_total" id="sub_total" placeholder="Sub Total" readonly
                            style="border:1px solid green" step="0.01">
                        </div>
                        <div class="form-group">
                            Browse Bus Ticket:
                            <input class="btn btn-default" type="file" name="image" id="imgInp">
                        </div>
                </table>
            </div>
        </div>

    
	




	
    </div>
 <div class="col-md-3">

    <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title"> Boarding Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <tr>
        <th>Boarding Point</th>
        <td>
            <div class="form-group" style="clear:left;"><br>
                                
                 <input type="text" class="form-control" name="boarding_point_taxivaxi" id="boarding_point_taxivaxi" placeholder="Boarding Point" value="<?php if($bookingData['response']['BookingDetail']['is_assign'] == '0') echo $bookingData['response']['BookingDetail']['boarding_point']; else echo $bookingData['response']['BookingDetail']['boarding_point_taxivaxi']; ?>" required>
             </div></td>
    </tr>

    <tr>
        <th>Boarding Time</th>
        <td>
            <div class="form-group">
                                
                                <input type="text" class="form-control" name="pickup_datetime_taxivaxi" id="pickup_datetime_taxivaxi" placeholder="Pickup Time" value="<?php if($bookingData['response']['BookingDetail']['is_assign'] == '0') echo $bookingData['response']['BookingDetail']['date_of_journey']; else echo $bookingData['response']['BookingDetail']['pickup_datetime_taxivaxi']; ?>" required>
                    </div>
        </td>
    </tr>

   
    </table>
    </div>
    </div>

    <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title">Passenger Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <?php for($i=1; $i<=(int)$companiesData['response']['BookingDetail']['no_of_seats']; $i++){ ?>
    <tr>
        <th>Employee Id</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_cid'] ?></td>
    </tr>
    <tr>
        <th>Name</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_name'] ?></td>
    </tr>
    <tr>
        <th>Contact Email</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_email'] ?></td>
    </tr>
    <tr>
        <th>Contact No</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_contact'] ?></td>
    </tr>
    <tr>
        <th>Age</th>
        <td><?php echo $companiesData['response']['BookingDetail']['age'] ?></td>
    </tr>
    <tr>
        <th>ID Proof Type</th>
        <td><?php echo $companiesData['response']['BookingDetail']['id_proof_type'] ?></td>
    </tr>
     <tr>
        <th>ID Proof No.</th>
        <td><?php echo $companiesData['response']['BookingDetail']['id_proof_no'] ?></td>
    </tr>
    <?php } ?>
   
    </table>
    </div>
    </div>
    </div>
<!--/span-->
</div><!--/row-->
<div class="row">
	<div class="col-md-12">
		<div class="box">
			<div class="box-body" style="text-align: center">
				 <input type="hidden" name="booking_id" value="<?php echo $bookingData['response']['BookingDetail']['id']; ?>">

                 <button type="submit" class="btn-block btn-lg btn-primary">RE-ASSIGN </button>
			</div>
		</div>
	</div>
</div>

    <?php echo $this->mess ;?>
</form>
</section>


















    <?php echo $this->mess ;?>
<script>
$(document).ready(function() {
    var options = {
        types: []
    };
    var input = document.getElementById('boarding_point_taxivaxi');
    var autocomplete = new google.maps.places.Autocomplete(input, options);

    $('#pickup_datetime_taxivaxi').daterangepicker({
        "singleDatePicker": true,
        "timePicker": true,
        "timePicker24Hour": true,
        "defaultDate": new Date(),
        locale: {
          format: 'YYYY-MM-DD HH:mm:ss'
        }
    });

    $("#total, #taxivaxi_tax_rate").change(function()
    {
        var total = parseFloat($('#total').val()).toFixed(2);
        var taxivaxi_charge = parseFloat($('#taxivaxi_charge').val()).toFixed(2);
        var taxivaxi_tax_rate = parseFloat($('#taxivaxi_tax_rate').val()).toFixed(2);
        var taxivaxi_tax_charge = parseFloat($('#taxivaxi_tax_charge').val()).toFixed(2);
        var sub_total = parseFloat($('#sub_total').val()).toFixed(2);

        var at = '<?php echo $_COOKIE["access_token_business_taxivaxi"]?>' ;
        

        if(!isNaN(parseInt(taxivaxi_tax_rate))&&!isNaN(parseInt(total)))
        {
            taxivaxi_tax_charge = parseFloat((parseFloat(taxivaxi_charge)*parseFloat(taxivaxi_tax_rate))/100).toFixed(2);

            $('#taxivaxi_tax_charge').val(taxivaxi_tax_charge);

            sub_total = parseFloat(parseFloat(total)+parseFloat(taxivaxi_charge)+parseFloat(taxivaxi_tax_charge)).toFixed(2);
            $('#sub_total').val(sub_total);
        }
    });
});
</script>