<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $bookingsData = json_decode($this->bookings, true);
    // echo $this->bookings;
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }
?>
<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">Archived Bus Bookings</div>

    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:11px">
                                <th style="width:5%" class="text-left">ID</th>
                                <th style="width:7%; text-align:left" >Pickup City</th>
                                <th style="width:7%; text-align:left" >Drop City</th>
                                <th style="width:13%; text-align:left" >Bookings DateTime</th>
                                <th style="width:20%; text-align:left" >Pickup DateTime Range</th>
                                <th style="width:10%; text-align:left" >Bus Type Requested</th>
                                <th style="width:10%; text-align:left" >Spoc Details</th>
                                <th style="width:10%; text-align:left" >Employee Details</th>
                                <th style="width:8%; text-align:left" >Taxivaxi Status</th>
                                <th style="width:5%; text-align:left" >Invoice</th>
                                <th style="width:5%; text-align:left" >Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){
                                    ?>
                            <tr style="font-size:11px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] .'<br>('.$bookingsData['response']['Bookings'][$i]['corporate_name'].')' ?></td>

                                <td style="text-align:left"><?php echo substr($bookingsData['response']['Bookings'][$i]['pickup_city'], 0, 20); ?></td>

                                <td style="text-align:left"><?php echo substr($bookingsData['response']['Bookings'][$i]['drop_city'], 0, 20); ?></td>

                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['created'])); ?></td>

                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime(explode("::",$bookingsData['response']['Bookings'][$i]['time_range'])[0])); ?> To 
                                    <?php echo date("d M Y - h:i a", strtotime(explode("::",$bookingsData['response']['Bookings'][$i]['time_range'])[1])); ?></td>

                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['bus_type_priority_1']; ?></td>

                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['user_name']." (".$bookingsData['response']['Bookings'][$i]['user_contact'].")"; ?></td>
                                
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['people_name']." (".$bookingsData['response']['Bookings'][$i]['people_contact'].")"; ?></td>

                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '0'){ ?>
                                        <p style="color:orange"><i class="fa fa-circle green" style="margin-right:5px"></i>Pending</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1') { ?>
                                        <p style="color:blue"><i class="fa fa-circle green" style="margin-right:5px"></i>Accepted</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '2') { ?>
                                        <p style="color:red"><i class="fa fa-circle green" style="margin-right:5px"></i>Rejected</p>
                                    <?php }else{?>
                                        <p style="color:green"><i class="fa fa-circle green" style="margin-right:5px"></i>Assigned</p>
                                    <?php }?>
                                </td>

                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_invoice'] == '0' 
                                          && $bookingsData['response']['Bookings'][$i]['is_assign'] == '1' ){ ?>
                                    <a id="addinvoice_group_button" \ 
                                    href="<?php echo '/taxivaxibooking/addInvoiceBus/'.$bookingsData['response']['Bookings'][$i]['id']; ?>">
                                        <i class="glyphicon glyphicon-plus icon-green"></i>
                                    </a>
                                    <?php }?>
                                </td>

                                <td style="text-align:left">
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="viewbooking_group_button" href="/businesstaxivaxi/viewBusBooking/<?php echo $l ; ?>" >
                                        <i class="glyphicon glyphicon-search icon-white"></i>
                                    </a>
                                </td>


                                <input type="hidden" name="status_auth_taxivaxi" id="status_auth_taxivaxi" value="<?php echo $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi']; ?>">

                                <input type="hidden" name="is_assign" id="is_assign" value="<?php echo $bookingsData['response']['Bookings'][$i]['is_assign']; ?>">

                                <input type="hidden" name="is_invoice" id="is_invoice" value="<?php echo $bookingsData['response']['Bookings'][$i]['is_invoice']; ?>">

                                <!-- <input type="hidden" name="tt" id="tt" value="<?php echo $bookingsData['response']['Bookings'][$i]['tour_type']; ?>"> -->

                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'aaSorting' : [[5,"ASC"]],
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

    $('#add_group_form').hide();
    $('#edit_group_form').hide();


    $('a').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#add_group_button').click(function(){
        $('#my_table').hide();
        $('#edit_group_form').hide();

        $('#group_name').val('');
        $('#budget').val();
        $('#auth_name').val();
        $('#auth_email').val();
        $('#auth_password').val();
        $('#is_radio').attr('checked', false);
        $('#is_outstation').attr('checked', false);
        $('#add_group_form').show();
    });

    $('#cancel_group_button, #cancel_group_button2').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#r').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_radio_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_radio_extra').val('Yes');
        }
    });

    $('#l').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_local_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_local_extra').val('Yes');
        }
    });

    $('#o').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_outstation_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_outstation_extra').val('Yes');
        }
    });

    $('.my_row').click(function(){
    });


    //For Accept Button
    /*$('.my_row').mouseover(function(){
        //If accepted, no need to show again
        if($(this).find('#status_auth_taxivaxi').val() != '1' && $(this).find('#status_auth_taxivaxi').val() != '3')
        {
            $(this).find('#accept_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#accept_group_button').hide();
    });*/

    //For BOOK Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#tt').val() == '0' && $(this).find('#status_auth_taxivaxi').val() == '1' && 
            $(this).find('#is_invoice').val() == '0')
        {
            $(this).find('#book_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#book_group_button').hide();
    });*/

    //For CANCEL BOOK Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#tt').val() == '0' && $(this).find('#is_assign').val() == '1' && $(this).find('#status_auth_taxivaxi').val() == '3' && $(this).find('#is_invoice').val() == '0')
        {
            $(this).find('#cancelbook_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#cancelbook_group_button').hide();
    });*/

    //For Reject Button
    /*$('.my_row').mouseover(function(){
        //If rejected, no need to show again
        if($(this).find('#status_auth_taxivaxi').val() != '2' && $(this).find('#status_auth_taxivaxi').val() != '3')
        {
            $(this).find('#reject_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#reject_group_button').hide();
    });*/

    //For Assign Button
    $('.my_row').mouseover(function(){
        //Show only if accepted by taxivaxi
        if($(this).find('#status_auth_taxivaxi').val() == '1')
        {
            $(this).find('#assign_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#assign_group_button').hide();
    });

    //Add Invoice Button
    /*$('.my_row').mouseover(function(){
        //Show only if accepted by taxivaxi
        if(($(this).find('#is_assign').val() == '1' && $(this).find('#is_invoice').val() == '0') )
        {
            $(this).find('#addinvoice_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#addinvoice_group_button').hide();
    });*/

    //View Invoice Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#is_invoice').val() == '1')
        {
            $(this).find('#viewinvoice_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#viewinvoice_group_button').hide();
    });*/
    
});
</script>

