<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>
<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $type = $this->type;

    $billsData = json_decode($this->bills, true);

    if(isset($billsData['response'])){
        $billsCount = count($billsData['response']['Bills']);
    }
    else{
        $billsCount = 0;
    }

?>

<?php echo $this->mess ;?>



<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'Unpaid-Bills';} else echo 'Paid Bills'; ?>
    </div>
    <div style="margin-left:470px; font-weight:bold; font-size:18px;"></div>
    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <div class="box-tools">
                        <?php if($type == '1') { ?>
                            <div class="input-group">
                                <button class="btn btn-sm btn-default" style="margin-left:5px; margin-top:7px"
                                id="multiple_button">Mark as Paid</button>
                            </div>
                        <?php } ?>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_bills">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <th>BILL ID</th>
                                <th>Company<br>Name</th>
                                <th>Bill Date</th>
                                <th>Bill Type</th>
                                <th>Bookings Included</th>
                                <th>Bill Amount</th>
                                <th>Payment Date</th>
                                <th>Payment Amount</th>
                                <th>Payment Mode</th>
                                <th>Account No</th>
                                <?php if($type == '1') { ?>
                                    <th>Mark as<br>Payment Done</th>
                                <?php } ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$billsCount; $i++){ ?>
                            <tr style="font-size:12px; cursor:pointer" class="my_row" id="<?php echo $billsData['response']['Bills'][$i]['id'] ?>">
                                <td><?php echo $billsData['response']['Bills'][$i]['bill_reference_no']; ?></td>
                                <td><?php echo $billsData['response']['Bills'][$i]['corporate_name']; ?></td>
                                <td style="text-align:left" class="bill_date"><?php echo date("d M Y", strtotime($billsData['response']['Bills'][$i]['created_at'])); ?></td>
                                <td style="text-align:left">
                                    <?php if($billsData['response']['Bills'][$i]['bill_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($billsData['response']['Bills'][$i]['bill_type'] == '1') { ?>
                                        Local
                                    <?php }elseif($billsData['response']['Bills'][$i]['bill_type'] == '2'){ ?>
                                        Outstation
                                    <?php }else{?>
                                        Bus
                                    <?php }?>
                                </td>
                                <td style="text-align:left">
                                    <?php 
                                    $split_array = explode(",", $billsData['response']['Bills'][$i]['booking_ids']);
                                    for($j=0; $j<count($split_array); $j++)
                                    {
                                        if($billsData['response']['Bills'][$i]['bill_type'] == '3') {
                                            echo "<a href='/businesstaxivaxi/viewBusBooking/".$split_array[$j]."'>"."TV".$billsData['response']['Bills'][$i]['corporate_code']."BUS".$split_array[$j].",</a> ";
                                        }
                                        else
                                        {
                                            echo "<a href='/businesstaxivaxi/viewBooking/".$split_array[$j]."'>"."TV".$billsData['response']['Bills'][$i]['corporate_code'].$split_array[$j].",</a> ";   
                                        }

                                    }?>
                                </td>
                                <td style="text-align:right">
                                    <?php if($billsData['response']['Bills'][$i]['bill_type'] == '3') { ?>
                                        <a id="viewbill_group_button" style="margin-left:23px;" class=" fa-trash" href="<?php echo '/taxivaxibooking/viewBusBill/'.$billsData['response']['Bills'][$i]['id']; ?>">
                                            <?php echo "Rs.".number_format((float)$billsData['response']['Bills'][$i]['bill_amount'], 2, '.', ''); ?>
                                        </a>
                                    <?php } else { ?>
                                        <a id="viewbill_group_button" style="margin-left:23px;" class=" fa-trash" href="<?php echo '/taxivaxibooking/viewBill/'.$billsData['response']['Bills'][$i]['id']; ?>">
                                            <?php echo "Rs.".number_format((float)$billsData['response']['Bills'][$i]['bill_amount'], 2, '.', ''); ?>
                                        </a>
                                    <?php } ?>

                                </td>
                                <?php if($type=='1') { ?>
                                <th>
                                    <input type="text" class="form-control payment_date" name="payment_date"  
                                    id="payment_date_<?php echo $billsData['response']['Bills'][$i]['id']; ?>" placeholder="Payment Date" required>
                                </th>
                                <th style="text-align:right">
                                    <input type="number" class="form-control" name="payment_amount"  id="payment_amount_<?php echo $billsData['response']['Bills'][$i]['id']; ?>" placeholder="Payment Amount" step="0.01" required>
                                </th>
                                <th>
                                    <input type="text" class="form-control" name="payment_mode"  
                                    id="payment_mode_<?php echo $billsData['response']['Bills'][$i]['id']; ?>" placeholder="Payment Mode" required>
                                </th>
                                <th>
                                    <input type="text" class="form-control" name="payment_account_no"  
                                    id="payment_account_no_<?php echo $billsData['response']['Bills'][$i]['id']; ?>" placeholder="Payment Account No" required>
                                </th>
                                <th>
                                    <button class="paid_bill" id="paid_bill_<?php echo $billsData['response']['Bills'][$i]['id'].'_'.$billsData['response']['Bills'][$i]['bill_type']; ?>">
                                        Paid
                                    </button>
                                </th>
                                <?php }else{ ?>
                                    <td style="text-align:left"><?php echo date("d M Y", strtotime($billsData['response']['Bills'][$i]['payment_date'])); ?></td>
                                    <td style="text-align:right"><?php echo number_format((float)$billsData['response']['Bills'][$i]['payment_amount'], 2, '.', ''); ?></td>
                                    <td style="text-align:left"><?php echo $billsData['response']['Bills'][$i]['payment_mode'] ?></td>
                                    <td style="text-align:left"><?php echo $billsData['response']['Bills'][$i]['payment_account_no'] ?></td>
                                <?php } ?>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    var type = '<?php echo $this->type; ?>';
    if(type=='1')
    {
        $('#table_bills').DataTable({
            'paging': true,
            'sort' : false,
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }
    else
    {
        $('#table_bills').DataTable({
            'paging': true,
            'sort' : false,
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        }); 
    }

    $("tr").each(function() {
        var bill_date = $(this).find("td.bill_date").html();
        $(this).find('.payment_date').daterangepicker({
            "singleDatePicker": true,
            "timePicker": false,
            locale: {
              format: 'YYYY-MM-DD'
            },
            minDate: new Date(bill_date)
        });
    });

    /*$('.payment_date').daterangepicker({
            "singleDatePicker": true,
            "timePicker": false,
            locale: {
              format: 'YYYY-MM-DD'
            }
        });*/
    

   //For Multiple Operation Button
    $('.paid_bill').click(function () {
        var fun = (function(url, at, bill_id, bill_type, payment_date, payment_amount, payment_mode, payment_account_no){
            jQuery.ajax({
                url: url,
                type: 'post',
                data: {
                    access_token: at,
                    bill_id: bill_id,
                    bill_type: bill_type,
                    payment_date: payment_date,
                    payment_amount: payment_amount,
                    payment_mode: payment_mode,
                    payment_account_no: payment_account_no
                },
                dataType: 'json',
                success: function (data) {
                },
                error: function(data)
                {
                }
            });
        });
        
        var at = '<?php echo $_COOKIE["access_token_business_taxivaxi"] ; ?>';
        var url = 'http://taxivaxi.in/business/api/billStatusPaid';
        
        var bill_id = $(this).attr('id').split("_")[2];
        var bill_type = $(this).attr('id').split("_")[3];
        var payment_date = $('#payment_date_'+bill_id).val();
        var payment_amount = $('#payment_amount_'+bill_id).val();
        var payment_mode = $('#payment_mode_'+bill_id).val();
        var payment_account_no = $('#payment_account_no_'+bill_id).val();

        fun(url, at, bill_id, bill_type, payment_date, payment_amount, payment_mode, payment_account_no);
        setTimeout(function(){ location.reload(); }, 1000);
    });

});
</script>

