<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>
<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $type = $this->type;

    $bookingsData = json_decode($this->bookings, true);
    
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'New Bus Invoices:Unbilled';} elseif($type=='2') echo 'Bus Invoices:Cleared by Spoc'; elseif($type=='6') echo 'Bus Invoices:Cleared for billing'; elseif($type=='3') echo 'Bus Invoices:Corrections/Comments from Client'; elseif($type=='4') echo 'Billed Bus Invoices:Unpaid'; elseif($type=='5') echo 'Paid Bus Invoices'; ?>
    </div>
    <div style="margin-left:470px; font-weight:bold; font-size:18px;"></div>
    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <div class="box-tools">
                        <?php if($type == '6' /*|| $type == '4'*/) { ?>
                            <div class="input-group">
                                <!-- <button class="btn btn-sm btn-default" style="margin-left:5px; margin-top:7px"
                                id="select_all_button"><?php if($type == '6') echo 'Select All'; ?></button> -->
                                <button class="btn btn-sm btn-default" style="margin-left:5px; margin-top:7px"
                                id="multiple_button"><?php if($type == '6') echo 'Create New Bill';/* else echo 'Mark as Paid';*/ ?></button>
                            </div>
                        <?php } ?>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_invoices">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <?php if($type == '6' /*|| $type =='4'*/){ ?>
                                    <th style="width:2%;"></th>
                                <?php } ?>
                                <th style="width:5%">Booking<br>ID</th>
                                <?php if($type == '4' || $type == '5'){ ?>
                                    <th style="width:6%">Bill ID</th>
                                <?php } ?>
                                <th style="width:5%">Company<br>Name</th>
                                <th style="width:5%">Operator Details</th>
                                <th style="width:10%">SPOC Details</th>
                                <th style="width:10%">Passenger Details</th>
                                <th style="width:5%">Pickup City</th>
                                <th style="width:5%">Drop City</th>
                                <th style="width:20%">Boarding Point</th>
                                <th style="width:15%">Invoice Details</th>
                                <?php if($type == '3') { ?>
                                    <th style="width:4%;">Requested<br>By</th>
                                    <th style="width:15%;">Client<br>Comment</th>
                                    <th style="width:15%;">Taxivaxi<br>Comment</th>
                                <?php } ?>
                                <!--<?php if($type == '6') { ?>
                                    <th style="width:12%;">Cleared By</th>
                                <?php } ?>-->
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){ ?>
                            <tr style="font-size:11px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <?php if($type == '6' /*|| $type=='4'*/){ ?>
                                <td><input type="checkbox" name="multiple_select" id="<?php echo $bookingsData['response']['Bookings'][$i]['invoice_id'] ; ?>" 
                                    class="<?php echo $bookingsData['response']['Bookings'][$i]['id'].'_ms' ; ?>"></td>
                                <?php } ?>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] ?></td>
                                <?php if($type == '4' || $type == '5'){ ?>
                                <td style="text-align:left">
                                    <a href="/taxivaxibooking/viewBusBill/<?php echo $bookingsData['response']['Bookings'][$i]['bill_id']; ?>">
                                        <?php echo $bookingsData['response']['Bookings'][$i]['corporate_code']."BILL".str_pad($bookingsData['response']['Bookings'][$i]['bill_id'], 4, "0", STR_PAD_LEFT); ?>
                                    </a>
                                </td>
                                <?php } ?>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['corporate_name'] ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['operator_name']."/".$bookingsData['response']['Bookings'][$i]['operator_contact']; ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['user_name']."/".$bookingsData['response']['Bookings'][$i]['user_contact']; ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['people_name']."/". $bookingsData['response']['Bookings'][$i]['people_contact'] ;?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['pickup_city']; ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['drop_city']; ?></td>
                                <td><?php echo substr($bookingsData['response']['Bookings'][$i]['boarding_point'], 0, 100); ?></td>
                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_invoice'] == '1'){ ?>

                                    <?php if($type=='1' || $type=='3') {?>
                                    <a style="float:left" id="editinvoice_group_button" href="<?php 
                                        echo '/taxivaxibooking/editInvoiceBus/'.$bookingsData['response']['Bookings'][$i]['invoice_id'];?>">
                                        <!-- <i class="glyphicon glyphicon-list-alt icon-green"></i> -->
                                        EDIT
                                    </a>
                                    <?php } ?>

                                    <a style="float:right" id="viewinvoice_group_button" href="<?php 
                                        echo '/taxivaxibooking/viewBusInvoice/'.$bookingsData['response']['Bookings'][$i]['invoice_id']; ?>">
                                        <?php echo "Rs.".number_format((float)$bookingsData['response']['Bookings'][$i]['bill_amount'], 2, '.', ''); ?>    
                                    </a>

                                    <?php } ?>
                                </td>
                                <?php if($type == '3') { ?>
                                    <th ><?php echo $bookingsData['response']['Bookings'][$i]['rejected_by']; ?></th>
                                    <td><?php echo $bookingsData['response']['Bookings'][$i]['invoice_comment_client']; ?></td>
                                    <td>
                                        <form action="/businesstaxivaxi/commentBusInvoice" method="POST">
                                            <input type="hidden" value="<?php echo $bookingsData['response']['Bookings'][$i]['invoice_id'] ?>" name="invoice_id">
                                            <textarea rows="4" cols="50" name="comment"></textarea>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </form>
                                    </td>
                                <?php } ?>
                                <!--<?php if($type == '2') { ?>
                                    <th ><?php echo $bookingsData['response']['Bookings'][$i]['accepted_by']; ?></th>
                                <?php } ?>-->
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {    

    var type = '<?php echo $this->type; ?>';
    if(type=='1')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });     
    }
    else if (type=='2')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'sort' : false,
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });  
    }
    else if (type=='5' || type=='4')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });  
    }
    else if (type=='6')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    // {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });  
    }
    else
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        }); 
    }

    //For Multiple Operation Button
    $('#multiple_button').click(function () {

        var fun = (function(url, at, accept_string, accept_string_booking_ids){
            jQuery.ajax({
                url: url,
                type: 'post',
                data: {
                    access_token: at,
                    invoice_ids: accept_string,
                    booking_ids: accept_string_booking_ids
                },
                dataType: 'json',
                success: function (data) {
                },
                error: function(data)
                {
                }
            });
        });

        var arr_accept_ids=[]; //Invoice Id
        var accept_string = '';

        var arr_accept_booking_ids=[]; //Booking Id 
        var accept_string_booking_ids = '';

        $("input:checkbox").each(function(){
            var $this = $(this);

            if($this.is(":checked"))
            {
                arr_accept_ids.push($this.attr("id").split("_")[0]);
                accept_string = accept_string + $this.attr("id").split("_")[0] + ",";

                arr_accept_booking_ids.push($this.attr("class").split("_")[0]);
                accept_string_booking_ids = accept_string_booking_ids + $this.attr("class").split("_")[0] + ",";
            }
        });

        var len = arr_accept_ids.length ;
        if(len > 0)
        {
            var at = '<?php echo $_COOKIE["access_token_business_taxivaxi"] ; ?>';

            var url = 'http://taxivaxi.in/business/api/businvoiceStatusBilled';
            
            fun(url, at, accept_string, accept_string_booking_ids);
            setTimeout(function(){ location.reload(); }, 1000);
        }
    });
    
    /*$('#select_all_button').click(function(){
        $("input:checkbox").each(function(){
            $(this).attr('checked','checked');
        });
    });*/

});
</script>

