<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $bookingsData = json_decode($this->bookings, true);
    // var_dump($bookingsData);
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }
?>
<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">Active Taxi Bookings (Unassigned)</div>
     <div style="text-align:right; float: right;">
        <a href="/taxivaxi/download/unassigned/booking/report"><button class="btn btn-success pull-right"><i class="fa fa-download"></i>&nbsp;&nbsp;&nbsp;Download</button></a>
    </div> 
	<br>
    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:11px">
                                <th style="text-align:left">ID</th>
                                <th style="text-align:left">City</th>
                                <th style="text-align:left" >Booking DateTime</th>
                                <th style="text-align:left" >Pickup DateTime</th>
                                <th style="text-align:left">Pickup Location</th>
                                <th style="text-align:left">Drop Location</th>
                                <th style="text-align:left" >Tour Type<br>(Requested Taxi)</th>
                                <th style="text-align:left">Taxivaxi Status</th>
                                <th style="text-align:left" >Accept/<br>Reject</th>
                                <th style="text-align:left" >Operator<br>Details</th>
                                <th style="text-align:left" >Taxi/Driver<br>Assign</th>
                                <th style="text-align:left" >Taxi/Driver Details</th>
                                <th style="text-align:left" >Passenger Details</th>
                                <th style="text-align:left" >OLA Reference No</th>
                                <th style="text-align:left" >Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){?>
                            <tr style="font-size:11px;" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">

                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] .'<br>('.$bookingsData['response']['Bookings'][$i]['corporate_name'].')' ?></td>
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['group_name'] ?></td>

                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['booking_date'])); ?></td>

                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['pickup_datetime'])); ?></td>

                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['pickup_location']; ?></td>

                                <td><?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '2') { echo $bookingsData['response']['Bookings'][$i]['drop_city_name']; } else{ echo $bookingsData['response']['Bookings'][$i]['drop_location']; } ?>
                                </td>

                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['tour_type'] == '1') { ?>
                                        Local
                                    <?php }else{ ?>
                                        Outstation
                                    <?php }?>
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){ ?>
                                    <?php }else{ if($bookingsData['response']['Bookings'][$i]['taxi_type_id'] == '1'){?>
                                        <br>(Sedan)
                                    <?php } else{ ?>
                                        <br>(SUV)
                                    <?php }} ?>
                                </td>

                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '0'){ ?>
                                        <p style="color:orange"><i class="fa fa-circle green" style="margin-right:5px"></i>Pending</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1') { ?>
                                        <p style="color:blue"><i class="fa fa-circle green" style="margin-right:5px"></i>Accepted</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '2') { ?>
                                        <p style="color:red"><i class="fa fa-circle green" style="margin-right:5px"></i>Rejected</p>
                                    <?php }else{?>
                                        <p style="color:green"><i class="fa fa-circle green" style="margin-right:5px"></i>Assigned</p>
                                    <?php }?>
                                </td>

                                <td class="right">
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] != '1' && $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] != '3') { ?>
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="accept_group_button" style="margin-left:10px;" class=" fa-trash" onclick="Confirm.render('Accept this Booking?', ' \/taxivaxibooking\/accept\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-ok icon-green"></i>
                                    </a>
                                    <?php } ?>
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] != '2' && $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] != '3') { ?>
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="reject_group_button" style="margin-left:10px;" class=" fa-trash" onclick="Confirm.render('Reject this Booking?', ' \/taxivaxibooking\/rejectreason\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-remove icon-green"></i>
                                    </a>
                                    <?php } ?>
                                </td>

                                <!-- Operator -->
                                <td style="text-align:left">
                                    <?php if(($bookingsData['response']['Bookings'][$i]['operator_name'] == '')
                                           &&($bookingsData['response']['Bookings'][$i]['is_assign'] == '0')
                                           &&($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1')){ ?>
                                           
                                           <input type="text" name="operator_name" id="operator_name<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="Operator name">
                                           <input type="email" name="operator_email" id="operator_email<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="email">
                                           <input type="text" name="operator_number" id="operator_number<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="contact no">
                                           <button id="assign_operator" value="<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" class="btn-flat btn-primary">ASSIGN</button>
                                    <?php }elseif (($bookingsData['response']['Bookings'][$i]['operator_name'] != '')
                                            &&($bookingsData['response']['Bookings'][$i]['is_assign'] == '0')
                                            &&(($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1'))) { echo $bookingsData['response']['Bookings'][$i]['operator_name'] . "<br><br>" ; ?>
                                            <input type="text" name="re_operator_name" id="re_operator_name<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="Operator name">
                                            <input type="email" name="re_operator_email" id="re_operator_email<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="email">
                                            <input type="text" name="re_operator_number" id="re_operator_number<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" placeholder="contact no">
                                            <button id="reassign_operator" value="<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>" class="btn-flat btn-success">REASSIGN</button>
                                    <?php }elseif(($bookingsData['response']['Bookings'][$i]['operator_name'] != '')
                                            &&($bookingsData['response']['Bookings'][$i]['is_assign'] == '1')){  
                                        echo $bookingsData['response']['Bookings'][$i]['operator_name'] ; 
                                    }?>
                                </td>

                                <td class="right">
                                    <!-- Local/Outstation -->
                                    <?php if(($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1') 
                                          &&($bookingsData['response']['Bookings'][$i]['tour_type'] != '0'))
                                           { ?>
                                            <a id="assign_taxi_driver_button"  class=" fa-trash" href="/taxivaxibooking/assign/<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>">
                                                <button class="btn-flat btn-primary">ASSIGN</button>
                                            </a>
                                    <?php } ?>
                                    <?php if(($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '3') 
                                          &&($bookingsData['response']['Bookings'][$i]['tour_type'] != '0'))
                                           { ?>
                                            <a id="reassign_taxi_driver_group_button"  class=" fa-trash" href="/taxivaxibooking/assign/<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>">
                                                <button class="btn-flat btn-success">RE-ASSIGN</button>
                                            </a>
                                    <?php } ?>
                                    <!-- Radio -->
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0' 
                                            && $bookingsData['response']['Bookings'][$i]['is_invoice'] == '0' 
                                            && $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1') 
                                            { ?>
                                            <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                            <a id="book_group_button"  class=" fa-trash" onclick="Confirm.render('Are you sure you want to book cab ?', ' \/taxivaxibooking\/book\/<?php echo $l ?> ');">
                                                <button class="btn btn-warning btn-sm">BOOK OLA</button>
                                            </a><br><br>
                                            <a href="/taxivaxibooking/assignRadio/<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>">
                                                <button id="assign_taxi_driver_button" class="btn btn-warning btn-sm">ASSIGN</button>
                                            </a>
                                    <?php } ?>
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0' 
                                            && $bookingsData['response']['Bookings'][$i]['is_assign'] == '1' 
                                            && $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '3' 
                                            && $bookingsData['response']['Bookings'][$i]['is_invoice'] == '0' ) 
                                            { ?>
                                            <!-- If OLA -->
                                            <?php if(strtolower($bookingsData['response']['Bookings'][$i]['operator_name']) == 'ola') {?>
                                                <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                                <a id="cancelbook_group_button"  class=" fa-trash" onclick="Confirm.render('Are you sure you want to cancel this booking ?', ' \/taxivaxibooking\/cancelbook\/<?php echo $l ?> ');">
                                                    <button class="btn btn-warning btn-sm">CANCEL OLA</button>
                                                </a><br><br>
                                                <a class=" fa-trash" href="/taxivaxibooking/reset/<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>">
                                                    <button class="btn btn-warning btn-sm">RESET</button>
                                                </a><br><br>
                                            <?php } else {?>
                                            <!-- If Not OLA -->
                                            <a href="/taxivaxibooking/assignRadio/<?php echo $bookingsData['response']['Bookings'][$i]['id']; ?>">
                                                <button id="assign_taxi_driver_button" class="btn btn-warning btn-sm">RE-ASSIGN</button>
                                            </a>
                                            <?php } ?>
                                    <?php } ?>
                                </td>

                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_assign'] == '1') { ?>
                                    <?php echo $bookingsData['response']['Bookings'][$i]['taxi_reg_no'] ; ?>/<?php echo $bookingsData['response']['Bookings'][$i]['driver_name'] ."<br>(".$bookingsData['response']['Bookings'][$i]['driver_contact'].")"; ?>
                                    <?php } ?>
                                </td>
                                <td style="text-align: left">
                                	<?php echo $bookingsData['response']['Bookings'][$i]['employee_name']. " (".$bookingsData['response']['Bookings'][$i]['employee_contact'].")"; ?>
                                </td>
								<td style="text-align:left">
                                    <?php $op_name = $bookingsData['response']['Bookings'][$i]['operator_name']; 
                                    	if($op_name == 'OLA')
                                    	{
											echo $bookingsData['response']['Bookings'][$i]['external_reference_no'];
										}
                                    ?>
                                </td>

                                <td class="right">
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="viewbooking_group_button"  class="fa-trash" href="/businesstaxivaxi/viewBooking/<?php echo $l ; ?>" style="margin-left:20px;">
                                        <i class="glyphicon glyphicon-search icon-white"></i>
                                    </a>
                                </td>


                                <input type="hidden" name="status_auth_taxivaxi" id="status_auth_taxivaxi" value="<?php echo $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi']; ?>">

                                <input type="hidden" name="is_assign" id="is_assign" value="<?php echo $bookingsData['response']['Bookings'][$i]['is_assign']; ?>">

                                <input type="hidden" name="is_invoice" id="is_invoice" value="<?php echo $bookingsData['response']['Bookings'][$i]['is_invoice']; ?>">

                                <input type="hidden" name="tt" id="tt" value="<?php echo $bookingsData['response']['Bookings'][$i]['tour_type']; ?>">

                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'sort': false,
        "stateSave": true,
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });


    //For Accept Button
    /*$('.my_row').mouseover(function(){
        //If accepted, no need to show again
        if($(this).find('#status_auth_taxivaxi').val() != '1' && $(this).find('#status_auth_taxivaxi').val() != '3')
        {
            $(this).find('#accept_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#accept_group_button').hide();
    });*/

    //For BOOK Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#tt').val() == '0' && $(this).find('#status_auth_taxivaxi').val() == '1' && 
            $(this).find('#is_invoice').val() == '0')
        {
            $(this).find('#book_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#book_group_button').hide();
    });*/

    //For CANCEL BOOK Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#tt').val() == '0' && $(this).find('#is_assign').val() == '1' && $(this).find('#status_auth_taxivaxi').val() == '3' && $(this).find('#is_invoice').val() == '0')
        {
            $(this).find('#cancelbook_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#cancelbook_group_button').hide();
    });*/

    //For Reject Button
    /*$('.my_row').mouseover(function(){
        //If rejected, no need to show again
        if($(this).find('#status_auth_taxivaxi').val() != '2' && $(this).find('#status_auth_taxivaxi').val() != '3')
        {
            $(this).find('#reject_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#reject_group_button').hide();
    });*/

    //For Assign Button
    /*$("#table_booking").on("mouseover", ".my_row", function(){
        //Show only if accepted by taxivaxi
        if($(this).find('#status_auth_taxivaxi').val() == '1' && $(this).find('#tt').val() != '0')
        {
            $(this).find('#assign_group_button').show();
        }
    });*/


    /*$("#table_booking").on("mouseover", ".my_row", function(){
        $(this).find('#assign_group_button').hide();
    });*/

    //Add Invoice Button
    /*$("#table_booking").on("mouseover", ".my_row", function(){
        //Show only if accepted by taxivaxi
        if(($(this).find('#is_assign').val() == '1' && $(this).find('#is_invoice').val() == '0') )
        {
            $(this).find('#addinvoice_group_button').show();
        }
    });

    $("#table_booking").on("mouseover", ".my_row", function(){
        $(this).find('#addinvoice_group_button').hide();
    });*/

    //View Invoice Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#is_invoice').val() == '1')
        {
            $(this).find('#viewinvoice_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#viewinvoice_group_button').hide();
    });*/

    $('#assign_operator').click(function(){
        var fun = (function(at, bi, name, email, contact_no){
            jQuery.ajax({
                url: 'http://taxivaxi.in/business/api/assignOperator',
                type: 'post',
                data: {
                    access_token: at,
                    booking_id: bi,
                    name: name,
                    email: email,
                    contact_no: contact_no
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if(data.success == '0')
                    {
                        alert('Error Assigning');
                    }
                    else
                    {
                        alert('Assigned Successfully');
                    }
                },
                error: function(data)
                {
                }
            });
        });
        var booking_id = $(this).attr("value");
        var name_id = '#operator_name'+booking_id;
        var email_id = '#operator_email'+booking_id;
        var contact_no_id = '#operator_number'+booking_id;
        var access_token = '<?php echo $_COOKIE["access_token_business_taxivaxi"]?>';
        var name = $(name_id).val();
        var email = $(email_id).val();
        var contact_no = $(contact_no_id).val();
        // alert(booking_id + " " + email + " " + contact_no);
        fun(access_token, booking_id, name, email, contact_no);
    });

    $('#reassign_operator').click(function(){
        var fun = (function(at, bi, name, email, contact_no){
            jQuery.ajax({
                url: 'http://taxivaxi.in/business/api/assignOperator',
                type: 'post',
                data: {
                    access_token: at,
                    booking_id: bi,
                    name: name,
                    email: email,
                    contact_no: contact_no
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if(data.success == '0')
                    {
                        alert('Error Assigning');
                    }
                    else
                    {
                        alert('Assigned Successfully');
                    }
                },
                error: function(data)
                {
                }
            });
        });
        var booking_id = $(this).attr("value");
        var rename_id = '#re_operator_name'+booking_id;
        var reemail_id = '#re_operator_email'+booking_id;
        var recontact_no_id = '#re_operator_number'+booking_id;
        var access_token = '<?php echo $_COOKIE["access_token_business_taxivaxi"]?>';
        var name = $(rename_id).val();
        var email = $(reemail_id).val();
        var contact_no = $(recontact_no_id).val();
        // alert(booking_id + " " + email + " " + contact_no);
        fun(access_token, booking_id, name, email, contact_no);
    });
    
});
</script>

