<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>
<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $type = $this->type;

    $bookingsData = json_decode($this->bookings, true);

    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'New Taxi Invoices:Unbilled';} elseif($type=='2') echo 'Taxi Invoices:Cleared by Spoc'; elseif($type=='6') echo 'Taxi Invoices:Cleared for billing'; elseif($type=='3') echo 'Taxi Invoices:Corrections/Comments from Client'; elseif($type=='4') echo 'Billed Taxi Invoices:Unpaid'; elseif($type=='5') echo 'Paid Taxi Invoices'; ?>
    </div>
    <div style="margin-left:470px; font-weight:bold; font-size:18px;"></div>
    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    <div class="box-tools">
                        <?php if($type == '6' /*|| $type == '4'*/) { ?>
                            <div class="input-group">
                                <button class="btn btn-sm btn-default" style="margin-left:5px; margin-top:7px"
                                id="multiple_button"><?php if($type == '6') echo 'Create New Bill';/* else echo 'Mark as Paid';*/ ?></button>
                            </div>
                        <?php } ?>
                    </div>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_invoices">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <?php if($type == '6' /*|| $type =='4'*/){ ?>
                                <th style="width:2%;"></th>
                                <?php } ?>
                                <th style="width:5%">Booking ID</th>
                                <?php if($type == '4' || $type == '5'){ ?>
                                    <th style="width:5%">Bill ID</th>
                                <?php } ?>
                                <th style="width:5%">Company<br>Name</th>
                                <th style="width:15%;" >Pickup DateTime</th>
                                <th style="width:14%;" >Spoc Id/Name</th>
                                <th style="width:5%; " >Tour Type</th>
                                <th style="width:18%;" >Pickup Location</th>
                                <th style="width:10%;" >Invoice Amount</th>
                                <?php if($type == '3') { ?>
                                    <th style="width:6%;">Requested<br>By</th>
                                    <th style="width:18%;">Client<br>Comment</th>
                                    <th style="width:18%;">Taxivaxi<br>Comment</th>
                                <?php } ?>
                                <!--<?php if($type == '2') { ?>
                                    <th style="width:12%;">Cleared By</th>
                                <?php } ?>-->
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){ ?>
                            <tr style="font-size:12px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <?php if($type == '6' /*|| $type=='4'*/){ ?>
                                <td><input type="checkbox" name="multiple_select" id="<?php echo $bookingsData['response']['Bookings'][$i]['invoice_id'].'_ms_'.$bookingsData['response']['Bookings'][$i]['tour_type'].'_'.$bookingsData['response']['Bookings'][$i]['admin_id'] ; ?>" 
                                    class="<?php echo $bookingsData['response']['Bookings'][$i]['id'].'_ms' ; ?>"></td>
                                <?php } ?>
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] ?></td>
                                <?php if($type == '4' || $type == '5'){ ?>
                                <td style="text-align:left">
                                    <a href="/taxivaxibooking/viewBill/<?php echo $bookingsData['response']['Bookings'][$i]['bill_id']; ?>">
                                        <?php echo $bookingsData['response']['Bookings'][$i]['corporate_code']."BILL".str_pad($bookingsData['response']['Bookings'][$i]['bill_id'], 4, "0", STR_PAD_LEFT); ?>
                                    </a>
                                </td>
                                <?php } ?>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['corporate_name'] ?></td>
                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['pickup_datetime'])); ?></td>
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['user_cid']."/". $bookingsData['response']['Bookings'][$i]['user_name'] ;?></td>
                                <td style="text-align:left">
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['tour_type'] == '1') { ?>
                                        Local
                                    <?php }elseif($bookingsData['response']['Bookings'][$i]['tour_type'] == '2'){ ?>
                                        Outstation
                                    <?php }?>
                                </td>
                                <input type="hidden" id="tt" value="<?php echo $bookingsData['response']['Bookings'][$i]['tour_type']; ?>">
                                <td style="text-align:left"><?php echo substr($bookingsData['response']['Bookings'][$i]['pickup_location'], 0, 100); ?></td>
                                <td style="text-align:right">
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_invoice'] == '1'){ ?>
                                    <a id="viewinvoice_group_button" href="<?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){
                                        echo '/taxivaxibooking/viewInvoiceRadio/'.$bookingsData['response']['Bookings'][$i]['invoice_id'];} else {
                                            echo '/taxivaxibooking/viewInvoiceOutstation/'.$bookingsData['response']['Bookings'][$i]['invoice_id']; }?>">
                                        <?php echo "Rs.".number_format((float)$bookingsData['response']['Bookings'][$i]['bill_amount'], 2, '.', ''); ?>
                                    </a>
                                    <?php if($type=='1' || $type == '3'){ ?>
                                        <a id="editinvoice_group_button" style="margin-left:30px" href="<?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){
                                        echo '/taxivaxibooking/editInvoiceRadio/'.$bookingsData['response']['Bookings'][$i]['invoice_id'];} elseif($bookingsData['response']['Bookings'][$i]['tour_type'] == '1') {
                                            echo '/taxivaxibooking/editInvoiceLocal/'.$bookingsData['response']['Bookings'][$i]['invoice_id']; } elseif($bookingsData['response']['Bookings'][$i]['tour_type'] == '2') {echo '/taxivaxibooking/editInvoiceOutstation/'.$bookingsData['response']['Bookings'][$i]['invoice_id'];}?>">
                                        <!-- <i class="glyphicon glyphicon-list-alt icon-green"></i> -->
                                        EDIT
                                        </a>
                                    <?php } ?>
                                    <?php } ?>
                                </td>
                                <?php if($type == '3') { ?>
                                    <th style="width:12%;"><?php echo $bookingsData['response']['Bookings'][$i]['rejected_by']; ?></th>
                                    <td><?php echo $bookingsData['response']['Bookings'][$i]['invoice_comment_client']; ?></td>
                                    <td>
                                        <form action="/businesstaxivaxi/commentInvoice" method="POST">
                                            <input type="hidden" value="<?php echo $bookingsData['response']['Bookings'][$i]['invoice_id'] ?>" name="invoice_id">
                                            <textarea rows="4" cols="50" name="comment"></textarea>
                                            <button type="submit" class="btn btn-primary">Submit</button>
                                        </form>
                                    </td>
                                <?php } ?>
                                <!--<?php if($type == '2') { ?>
                                    <th style="width:12%;"><?php echo $bookingsData['response']['Bookings'][$i]['accepted_by']; ?></th>
                                <?php } ?>-->
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    var type = '<?php echo $this->type; ?>';
    if(type=='1' || type == '2')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });     
    }
    else if (type=='5' || type=='4')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });  
    }
    else if (type=='6')
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    // {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });  
    }
    else
    {
        $('#table_invoices').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        }); 
    }
    

   //For Multiple Operation Button
    $('#multiple_button').click(function () {
        var b_id = '';
        var fun = (function(url, at, accept_string, accept_string_booking_ids, t){
            jQuery.ajax({
                url: url,
                type: 'post',
                data: {
                    access_token: at,
                    invoice_ids: accept_string,
                    booking_ids: accept_string_booking_ids,
                    tour_type: t
                },
                dataType: 'json',
                success: function (data) {
                    b_id = data.bill_id;
                },
                error: function(data)
                {
                }
            });
        });

        var arr_accept_ids=[]; //Invoice Id
        var accept_string = '';

        var tour_type_ids=[]; 
        var admin_ids=[]; 

        var arr_accept_booking_ids=[]; //Booking Id 
        var accept_string_booking_ids = '';

        $("input:checkbox").each(function(){
            var $this = $(this);

            if($this.is(":checked"))
            {
                arr_accept_ids.push($this.attr("id").split("_")[0]);
                accept_string = accept_string + $this.attr("id").split("_")[0] + ",";

                tour_type_ids.push($this.attr("id").split("_")[2]);
                admin_ids.push($this.attr("id").split("_")[3]);

                arr_accept_booking_ids.push($this.attr("class").split("_")[0]);
                accept_string_booking_ids = accept_string_booking_ids + $this.attr("class").split("_")[0] + ",";
            }
        });

        var len = arr_accept_ids.length ;
        if(len > 0)
        {
            if(len == 1)
            {
                var at = '<?php echo $_COOKIE["access_token_business_taxivaxi"] ; ?>';
                var url='';
                if(type == '6')
                    url = 'http://taxivaxi.in/business/api/invoiceStatusBilled';
                else if(type == '4')
                    url = 'http://taxivaxi.in/business/api/invoiceStatusPaid';
                fun(url, at, accept_string, accept_string_booking_ids, tour_type_ids[0]);
                setTimeout(function(){ 
                    var date = new Date();
                    date.setTime(date.getTime()+(10*1000));
                    var expires = "; expires="+date.toGMTString();

                    document.cookie = 'success'+"="+'Billing Created Successfully with Id:'+b_id+expires+"; path=/";
                    location.reload(); 
                }, 1000);
            }
            else
            {
                t = tour_type_ids[0];
                flag = 0;
                for(i=0; i<len; i++)
                {
                    if(tour_type_ids[i]!=t)
                    {
                        alert('Select Booking of one type only!!');
                        flag=1;
                        break;
                    }
                }

                a = admin_ids[0];
                flag2 = 0;
                for(i=0; i<len; i++)
                {
                    if(admin_ids[i]!=a)
                    {
                        alert('Select Booking of same company!!');
                        flag2=1;
                        break;
                    }
                }

                if(flag==0 && flag2==0)
                {
                    var at = '<?php echo $_COOKIE["access_token_business_taxivaxi"] ; ?>';
                    var url='';
                    if(type == '6')
                        url = 'http://taxivaxi.in/business/api/invoiceStatusBilled';
                    else if(type == '4')
                        url = 'http://taxivaxi.in/business/api/business/testapi/invoiceStatusPaid';
                    fun(url, at, accept_string, accept_string_booking_ids, t);
                    setTimeout(function(){
                        var date = new Date();
                        date.setTime(date.getTime()+(10*1000));
                        var expires = "; expires="+date.toGMTString();

                        document.cookie = 'success'+"="+'Billing Created Successfully with Id:'+b_id+expires+"; path=/";
                        location.reload(); 
                    }, 1000);
                }
            }
        }
    });

});
</script>

