<div id="add_group_form" class="box box-primary">
    <div class="box-header">
        <h3 class="box-title">Enter Reason for Cancelation/Rejection</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/taxivaxibooking/reject/<?php echo $this->booking_id ?>" method="POST" role="form">
        <div class="box-body">

            <div class="control-group">
                <label class="control-label" for="selectError">Reason</label>
                    <div class="controls">
                        <textarea rows="4" cols="50"  name="reason_cancel" id="reason_cancel" data-rel="chosen" required>
                        </textarea>
                    </div>
                </label>
            </div><br>

         <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            
        </div>    
       
    </form>
</div>