<?php 
    echo $this->headStyle()->appendStyle('/css/RegistrationForm.css');
    //echo $this->inlineScript()->appendFile('/js/jquery.validate.min.js')->appendFile('/js/additional-methods.min.js');


    $companiesData = json_decode($this->booking, true);
?>

<section class="content" style="font-size: 12px">

<div class="row">
    <div class="col-md-3">
        <div class="box">
            <div class="box-header" data-original-title="">
                <h2 class="box-title">Booking Details: <?php echo $companiesData['response']['BookingDetail']['reference_no']; ?>
                </h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Booking Id</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['reference_no']; ?></td>
                    </tr>

                    <?php if($companiesData['response']['BookingDetail']['tour_type'] == '0' && $companiesData['response']['BookingDetail']['is_assign'] == '1') { ?>
                    <tr>
                        <th>OLA Reference No</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['external_reference_no']; ?></td>
                    </tr>
                    <?php } ?>

                    <?php if($companiesData['response']['BookingDetail']['tour_type'] == '2') { ?>
                    <tr>
                        <th>Days</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['days']; ?></td>
                    </tr>
                    <?php } ?>

                    <tr>
                        <th>Tour Type</th>
                        <td><?php if($companiesData['response']['BookingDetail']['tour_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($companiesData['response']['BookingDetail']['tour_type'] == '1') { ?>
                                        Local
                                    <?php }else{ ?>
                                        Outstation
                                    <?php }?></td>
                    </tr>
                    <tr>
                        <th>Pickup Location</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['pickup_location']; ?></td>
                    </tr>
                    <tr>
                        <th>Booking Date</th>
                        <td><?php echo date("d M Y - h:i a", strtotime($companiesData['response']['BookingDetail']['booking_date'])); ?></td>
                    </tr>
                    <tr>
                        <th>Pickup DateTime</th>
                        <td><?php echo date("d M Y - h:i a", strtotime($companiesData['response']['BookingDetail']['pickup_datetime'])); ?></td>
                    </tr>

                    <tr>
                        <th>Status</th>
                        <td><?php if($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '0'){ ?>Pending
                            <?php }elseif ($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '1') { ?>Accepted
                            <?php }elseif ($companiesData['response']['BookingDetail']['status_auth_taxivaxi'] == '2') { ?>Rejected
                            <?php }else{?>Assigned
                            <?php }?>
                        </td>
                    </tr>
                    <tr>
                        <th>Assessment Code</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['ass_code']; ?></td>
                    </tr>
                    <tr>
                        <th>Reason for Booking</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['reason_booking']; ?></td>
                    </tr>
                </table>
            </div>
        </div>
		
    </div>

 <div class="col-md-3">
            <div class="box">
                <div class="box-header" data-original-title="">
                    <h2 class="box-title">Package Details</h2>
                </div>
                <div class="box-body">
                    <table class="table table-striped table-bordered">
                    	<?php if($companiesData['response']['BookingDetail']['tour_type'] != '0'){ ?>
	                        			<tr>
                            <th>Package Name</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['rate_name']; ?></td>
                        </tr>

	                        			<tr>
                            <th>Kms Included</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['kms']; ?></td>
                        </tr>
	                        			<tr>
                            <th>Hours Included</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['hours']; ?></td>
                        </tr>
	                        			<tr>
                            <th>Extra Km Rate(Rs)</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['km_rate']; ?></td>
                        </tr>
	                        			<tr>
                            <th>Extra Hour Rate(Rs)</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['hour_rate']; ?></td>
                        </tr>
	                     	 			<tr>
                            <th>Base Rate(Rs)</th>
                            <td><?php echo $companiesData['response']['BookingDetail']['base_rate']; ?></td>
                        </tr>
						<?php }
						else
						{?> 
						<tr><td colspan="2" style="color: red">No Package Details in case of Radio Taxi</td></tr>
						<?php } ?>
                    </table>
                </div>
            </div>
		<div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title">Operator Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <tr>
        <th>Operator Name</th>
        <td><div class="form-group" style="clear:left;">
                                
                                <input type="text" class="form-control" name="operator_name" id="operator_name" placeholder="Operator Name" value="<?php echo $companiesData['response']['BookingDetail']['operator_name']; ?>" readonly>
                            </div></td>
    </tr>
    
    <!-- <tr>
        <th>Operator Contact</th>
        <td><div class="form-group" style="clear:left;">
                              
                                <input type="text" class="form-control" name="operator_contact" id="operator_contact" placeholder="Operator Contact" value="<?php echo $companiesData['response']['BookingDetail']['operator_contact']; ?>" required>
                            </div></td>
    </tr>

    <tr>
        <th>Operator Email</th>
        <td><div class="form-group" style="clear:left;">
                                <input type="text" class="form-control" name="operator_email" id="operator_email" placeholder="Operator Email" value="<?php echo $companiesData['response']['BookingDetail']['operator_email']; ?>" required>
                            </div></td>
    </tr> -->
   
    </table>
    </div>
    </div>

    <div class="box">
            <div class="box-header" data-original-title="">
                <h2 class="box-title">Spoc Details</h2>
            </div>
            <div class="box-body">
                <table class="table table-striped table-bordered">
                    <tr>
                        <th>Spoc Name</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['user_name'] ?></td>
                    </tr>
                    <tr>
                        <th>Spoc Contact Email</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['user_email'] ?></td>
                    </tr>

                    <tr>
                        <th>Spoc Contact No</th>
                        <td><?php echo $companiesData['response']['BookingDetail']['user_contact'] ?></td>
                    </tr>
                </table>
            </div>
        </div>
		
 </div>


	<div class="col-md-3">
 <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title"> Driver Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <tr>
        <th>Driver Name</th>
        <td><?php echo $companiesData['response']['BookingDetail']['driver_name']; ?></td>
    </tr>

    <tr>
        <th>Driver Contact No</th>
        <td><?php echo $companiesData['response']['BookingDetail']['driver_contact']; ?></td>
    </tr>
   
    </table>
    </div>
    </div>
	<div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title"> Taxi Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    <tr>
        <th>Taxi Type</th>
        <td><?php if($companiesData['response']['BookingDetail']['tour_type'] != '0'){if($companiesData['response']['BookingDetail']['taxi_type_id'] == 1) echo 'Sedan'; else echo 'SUV'; }else {echo $companiesData['response']['BookingDetail']['taxi_type_name'];} ?></td>
    </tr>
    <tr>
        <th>Taxi Model Name</th>
        <td><?php if($companiesData['response']['BookingDetail']['tour_type'] != '0'){echo $companiesData['response']['BookingDetail']['taxi_model_name_o'];}else {echo $companiesData['response']['BookingDetail']['taxi_model_name'];} ?></td>
    </tr>

    <tr>
        <th>Taxi Reg No</th>
        <td><?php echo $companiesData['response']['BookingDetail']['taxi_reg_no']; ?></td>
    </tr>

   
    </table>
    </div>
    </div>

    <div class="box">
        <div class="box-header" data-original-title="">
            <h2 class="box-title"> Billing Details</h2>
        </div>
        <div class="box-body">
        <table class="table table-striped table-bordered">
        
        
            <tr>
                <th>Total Amount</th>
                <td>Rs.<?php echo number_format((float)$companiesData['response']['BookingDetail']['total'], 2, '.', ''); ?></td>
            </tr>
       
        </table>
        </div>
        </div>
        
    </div>
<div class="col-md-3">
    <div class="box">
    <div class="box-header" data-original-title="">
        <h2 class="box-title">Passenger Details</h2>
    </div>
    <div class="box-body">
    <table class="table table-striped table-bordered">
    
    <?php for($i=1; $i<=(int)$companiesData['response']['BookingDetail']['no_of_seats']; $i++){ ?>
    <tr>
        <th style="width:350px">Passenger <?php echo $i; ?> Employee Id</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_cid'] ?></td>
    </tr>
    <tr>
        <th style="width:350px">Passenger <?php echo $i; ?> Name</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_name'] ?></td>
    </tr>
    <tr>
        <th>Passenger <?php echo $i; ?> Contact Email</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_email'] ?></td>
    </tr>
    <tr>
        <th>Passenger <?php echo $i; ?> Contact No</th>
        <td><?php echo $companiesData['response']['BookingDetail']['People'][$i-1]['people_contact'] ?></td>
    </tr>
    <tr>
        <th></th>
        <th></th>
    </tr>
    <?php } ?>
   
    </table>
    </div>
    </div>
    </div>
<!--/span-->
</div><!--/row-->

 
   <!--  <img src="<?php echo $companiesData['response']['BookingDetail']['duty_slip'] ; ?>" alt="Mountain View" style="width:304px;height:228px;"> -->


    <?php echo $this->mess ;?>
</section>


<script>
$(document).ready(function() {

  
    $('#assign_operator').click(function(){
        var fun = (function(at, bi, name, email, contact_no){
            jQuery.ajax({
                url: 'http://taxivaxi.in/business/api/assignOperator',
                type: 'post',
                data: {
                    access_token: at,
                    booking_id: bi,
                    name: name,
                    email: email,
                    contact_no: contact_no
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if(data.success == '0')
                    {
                        alert('Error Assigning');
                    }
                    else
                    {
                        alert('Assigned Successfully');
                    }
                },
                error: function(data)
                {
                }
            });
        });
       var booking_id = "<?php echo $companiesData['response']['BookingDetail']['id'] ?>";
        var name_id = '#operator_name'+booking_id;
        var email_id = '#operator_email'+booking_id;
        var contact_no_id = '#operator_number'+booking_id;
        var access_token = '<?php echo $_COOKIE["access_token_business_taxivaxi"]?>';
        var name = $('#operator_name').val();
        var email = $('#operator_email').val();
        var contact_no = $('#operator_contact').val();
        // alert(booking_id + " " + email + " " + contact_no);
        fun(access_token, booking_id, name, email, contact_no);
    });

    $('#reassign_operator').click(function(){
        var fun = (function(at, bi, name, email, contact_no){
            jQuery.ajax({
                url: 'http://taxivaxi.in/business/api/assignOperator',
                type: 'post',
                data: {
                    access_token: at,
                    booking_id: bi,
                    name: name,
                    email: email,
                    contact_no: contact_no
                },
                dataType: 'json',
                success: function (data) {
                    console.log(data);
                    if(data.success == '0')
                    {
                        alert('Error Assigning');
                    }
                    else
                    {
                        alert('Assigned Successfully');
                    }
                },
                error: function(data)
                {
                }
            });
        });
        var booking_id = "<?php echo $companiesData['response']['BookingDetail']['id'] ?>";
     
        var rename_id = '#re_operator_name'+booking_id;
        var reemail_id = '#re_operator_email'+booking_id;
        var recontact_no_id = '#re_operator_number'+booking_id;
        var access_token = '<?php echo $_COOKIE["access_token_business_taxivaxi"]?>';
        var name = $(rename_id).val();
        var email = $(reemail_id).val();
        var contact_no = $(recontact_no_id).val();
        // alert(booking_id + " " + email + " " + contact_no);
        fun(access_token, booking_id, name, email, contact_no);
    });
    
});
</script>














