<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php
    $bookingsData = json_decode($this->bookings, true);
    // var_dump($bookingsData);
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }

    $type = $this->type;

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'Active Taxi Bookings:Unassigned';} elseif($type=='2') echo 'Active Taxi Bookings:Assigned'; elseif($type=='3') echo 'Archived Taxi Bookings'; elseif($type=='4') echo 'Cancelled/Rejected Taxi Bookings';?>
    </div>

    <div style="text-align:right; float: right;">
    	<!-- <input style="padding: 5px; line-height: 20px" type="text" id="report_daterange" name="report_daterange" />-->
    	<!--<div class="input-group">
                                            <div class="input-group-addon">
                                                <i class="fa fa-calendar"></i>
                                            </div>
                                            <input class="pull-right" id="reservation" type="text">
                                        </div>-->
        <a href="http://business.taxivaxi.in/download/booking/report" target="_blank"><button class="btn btn-success pull-right"><i class="fa fa-download"></i>&nbsp;&nbsp;&nbsp;Download Booking Report</button></a>
    </div> 
    

    <div class="row" style="padding-top:50px">

        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <th>ID</th>
                                <th>Tour Type</th>
                                <th>Sub-Region</th>
                                <th>Pickup Location</th>
                                <th>Drop Location</th>
                                <th>Booking DateTime</th>
                                <th>Pickup DateTime</th>
                                <?php if($_COOKIE['has_auth_level'] == '1') {?>
                                    <th>Approver Status</th>
                                    <th>Accepted/ Rejected By (Approver)</th>
                                <?php } ?>
                                <th>Taxivaxi Status</th>
                                <th>Booking Status By Spoc</th>
                                <th>Details</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){ ?>
                            <tr style="font-size:11px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] ?></td>
                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['tour_type'] == '1') { ?>
                                        Local
                                    <?php }else{ ?>
                                        Outstation
                                    <?php }?>
                                </td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['subgroup_name'] ; ?></td> 
                                <td><?php echo substr($bookingsData['response']['Bookings'][$i]['pickup_location'], 0, 20); ?></td>
                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['tour_type'] == '2') { echo $bookingsData['response']['Bookings'][$i]['drop_city_name']; } else{ echo substr($bookingsData['response']['Bookings'][$i]['drop_location'], 0, 20); } ?>
                                </td>
                                <td><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['created'])); ?></td>
                                <td><?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['pickup_datetime'])); ?></td>
                                <?php if($_COOKIE['has_auth_level'] == '1') {?>
                                    <td>
                                        <?php if(
                                             $bookingsData['response']['Bookings'][$i]['status_auth2'] == '0' &&
                                             $bookingsData['response']['Bookings'][$i]['status_auth1'] == '0'){ ?>
                                            <p style="color:orange"><i class="fa fa-circle green" style="margin-right:1px"></i>Pending</p>
                                        <?php }elseif (
                                            $bookingsData['response']['Bookings'][$i]['status_auth2'] == '1' ||
                                            $bookingsData['response']['Bookings'][$i]['status_auth1'] == '1') { ?>
                                            <p style="color:blue"><i class="fa fa-circle green" style="margin-right:1px"></i>Accepted<br>(<?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['approved_date'])); ?>)</p>
                                        <?php }else{ ?>
                                            <p style="color:red"><i class="fa fa-circle green" style="margin-right:1px"></i>Rejected<br>(<?php echo date("d M Y - h:i a", strtotime($bookingsData['response']['Bookings'][$i]['rejected_date'])); ?>)</p>
                                        <?php }?>
                                    </td>
                                    <td>
                                        <?php if(
                                             $bookingsData['response']['Bookings'][$i]['status_auth2'] == '0' &&
                                             $bookingsData['response']['Bookings'][$i]['status_auth1'] == '0'){ ?>
                                            <p style="color:orange"></p>
                                        <?php }elseif (
                                            $bookingsData['response']['Bookings'][$i]['status_auth2'] == '1' ||
                                            $bookingsData['response']['Bookings'][$i]['status_auth1'] == '1') { ?>
                                            <p style="color:blue">
                                                <?php if($bookingsData['response']['Bookings'][$i]['status_auth2'] == '1') {?>
                                                    Approver 2
                                                <?php }else{ ?>
                                                    Approver 1
                                                <?php } ?>
                                            </p>
                                        <?php }else{ ?>
                                            <p style="color:red">
                                                <?php if($bookingsData['response']['Bookings'][$i]['status_auth2'] == '2') {?>
                                                    Approver 2
                                                <?php }else{ ?>
                                                    Approver 1
                                                <?php } ?>
                                            </p>
                                        <?php }?>
                                    </td>
                                <?php } ?>
                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '0'){ ?>
                                        <p style="color:orange"><i class="fa fa-circle green" style="margin-right:5px"></i>Pending</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '1') { ?>
                                        <p style="color:blue"><i class="fa fa-circle green" style="margin-right:5px"></i>Accepted</p>
                                    <?php }elseif ($bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi'] == '2') { ?>
                                        <p style="color:red"><i class="fa fa-circle green" style="margin-right:5px"></i>Rejected</p>
                                    <?php }else{?>
                                        <p style="color:green"><i class="fa fa-circle green" style="margin-right:5px"></i>Assigned</p>
                                    <?php }?>
                                </td>

                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['status_user'] == '1'){ ?>
                                        <p style="color:blue"><i class="fa fa-circle green" style="margin-right:5px"></i>Active</p>
                                    <?php }else { ?>
                                        <p style="color:red"><i class="fa fa-circle green" style="margin-right:5px"></i>Cancelled</p>
                                    <?php } ?>
                                </td>

                                <td>
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="viewbooking_group_button"  class="fa-trash" href="/businessadmin/viewBooking/<?php echo $l ; ?>" >
                                        <i class="glyphicon glyphicon-search icon-white"></i>
                                    </a>
                                </td>

                                <!-- <td class="right">
                                    <?php $l = $bookingsData['response']['Bookings'][$i]['id']; ?>
                                    <a id="delete_group_button" style="display:none" class=" fa-trash" onclick="Confirm.render('Delete this Group?', ' \/adminbooking\/delete\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                    </a>
                                </td> -->

                                <input type="hidden" name="status_auth_taxivaxi" id="status_auth_taxivaxi" value="<?php echo $bookingsData['response']['Bookings'][$i]['status_auth_taxivaxi']; ?>">

                                <input type="hidden" name="is_invoice" id="is_invoice" value="<?php echo $bookingsData['response']['Bookings'][$i]['is_invoice']; ?>">

                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    var has_auth_level = '<?php echo $_COOKIE["has_auth_level"] ?>';
    if(has_auth_level == '1')
    {
        $('#table_booking').DataTable({
            'paging': true,
            'sort' : false,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }
    else
    {
        $('#table_booking').DataTable({
            'paging': true,
            'sort' : false,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }

  

    $('#add_group_form').hide();
    $('#edit_group_form').hide();


    $('a').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#add_group_button').click(function(){
        $('#my_table').hide();
        $('#edit_group_form').hide();

        $('#group_name').val('');
        $('#budget').val();
        $('#auth_name').val();
        $('#auth_email').val();
        $('#auth_password').val();
        $('#is_radio').attr('checked', false);
        $('#is_outstation').attr('checked', false);
        $('#add_group_form').show();
    });

    $('#cancel_group_button, #cancel_group_button2').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#r').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_radio_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_radio_extra').val('Yes');
        }
    });

    $('#l').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_local_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_local_extra').val('Yes');
        }
    });

    $('#o').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_outstation_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_outstation_extra').val('Yes');
        }
    });

    $('.my_row').click(function(){
    });
    
   /*$(function(){
   		alert("I am here");
   		$('#report_daterange').daterangepicker({
        locale: {
          format: 'YYYY-MM-DD HH:mm:ss'
        }
    });
   });*/
   
    
    //For Delete Button
    /*$('.my_row').mouseover(function(){
        //If accepted by taxivaxi cannot delete
        if($(this).find('#status_auth_taxivaxi').val() != '1' && $(this).find('#status_auth_taxivaxi').val() != '3')
        {
            $(this).find('#delete_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#delete_group_button').hide();
    });*/

    //View Invoice Button
    /*$('.my_row').mouseover(function(){
        if($(this).find('#is_invoice').val() == '1')
        {
            $(this).find('#viewinvoice_group_button').show();
        }
    });

    $('.my_row').mouseout(function(){
        $(this).find('#viewinvoice_group_button').hide();
    });*/
    
});
</script>

