<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>
<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $bookingsData = json_decode($this->bookings, true);
    if(isset($bookingsData['response'])){
        $bookingsCount = count($bookingsData['response']['Bookings']);
    }
    else{
        $bookingsCount = 0;
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'New Bus Invoices:Unbilled';} elseif($type=='2') echo 'Bus Invoices:Cleared for billing by Spoc'; elseif($type=='7') echo 'Bus Invoices:Corrections/Comments needed'; elseif($type=='4') echo 'Billed Bus Invoices:Unpaid'; elseif($type=='5') echo 'Paid Bus Invoices'; elseif($type=='6') echo 'Bus Invoices:Cleared for billing'; ?>
    </div>
    <div style="margin-left:470px; font-weight:bold; font-size:25px;"></div>

    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:15px">
                                <th style="width:5%"> Booking ID</th>
                                <?php if($type == '4' || $type == '5'){ ?>
                                    <th style="width:5%">Bill ID</th>
                                <?php } ?>
                                <th style="width:5%">Operator Details</th>
                                <th style="width:5%">SPOC Setails</th>
                                <th style="width:10%">Passenger Details</th>
                                <th style="width:5%">Pickup City</th>
                                <th style="width:5%">Drop City</th>
                                <th style="width:20%">Boarding Point</th>
                                <th style="width:15%">Invoice Amount</th>
                                <?php if($type == '2') { ?>
                                    <th style="width:5%;">Clear for<br>Billing</th>
                                    <th style="width:25%;">Correction/<br>Comment Needed</th>
                                <?php } ?>
                                <?php if($type == '7') { ?>
                                    <th style="width:6%;">Requested<br>By</th>
                                    <th style="width:6%;">Clear for<br>Billing</th>
                                    <th style="width:12%;">Client<br>Comment</th>
                                    <th style="width:12%;">Taxivaxi<br>Comment</th>
                                <?php } ?>
                                <!--<?php if($type == '2') { ?>
                                    <th style="width:12%;">Cleared By</th>
                                <?php } ?>-->
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$bookingsCount; $i++){ ?>
                            <tr style="font-size:12px; cursor:pointer" class="my_row" id="<?php echo $bookingsData['response']['Bookings'][$i]['id'] ?>">
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['reference_no'] ?></td>
                                <?php if($type == '4' || $type == '5'){ ?>
                                <td style="text-align:left">
                                    <a href="/adminbooking/viewBusBill/<?php echo $bookingsData['response']['Bookings'][$i]['bill_id']; ?>">
                                        <?php echo $bookingsData['response']['Bookings'][$i]['corporate_code']."BILL".str_pad($bookingsData['response']['Bookings'][$i]['bill_id'], 4, "0", STR_PAD_LEFT); ?>
                                    </a>
                                </td>
                                <?php } ?>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['operator_name']."/".$bookingsData['response']['Bookings'][$i]['operator_contact']; ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['user_name']."/".$bookingsData['response']['Bookings'][$i]['user_contact']; ?></td>
                                <td><?php echo $bookingsData['response']['Bookings'][$i]['people_name']."/". $bookingsData['response']['Bookings'][$i]['people_contact'] ;?></td>
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['pickup_city']; ?></td>
                                <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['drop_city']; ?></td>
                                <td style="text-align:left"><?php echo substr($bookingsData['response']['Bookings'][$i]['boarding_point'], 0, 100); ?></td>
                                <td>
                                    <?php if($bookingsData['response']['Bookings'][$i]['is_invoice'] == '1'){ ?>
                                    <a style="float:right" id="viewinvoice_group_button" href="<?php 
                                        echo '/businessadmin/viewBusinvoice/'.$bookingsData['response']['Bookings'][$i]['invoice_id']; ?>">
                                        <?php echo "Rs.".number_format((float)$bookingsData['response']['Bookings'][$i]['bill_amount'], 2, '.', ''); ?>    
                                    </a>
                                    <?php } ?>
                                </td>
                                <?php if($type == '2') { ?>
                                    <td style="text-align:left">
                                        <a id="clear_invoice_button" href="<?php echo '/businessadmin/clearBusInvoice/'.$bookingsData['response']['Bookings'][$i]['invoice_id']."/2"; ?>">
                                            Approve
                                        </a> 
                                    </td>
                                    <td style="text-align:left">
                                        <a href="/businessadmin/getComment/<?php echo $bookingsData['response']['Bookings'][$i]['invoice_id']?>/2"><!-- This 2 denotes Bus Invoice -->
                                            Add comment
                                        </a>
                                    </td>
                                <?php } ?>
                                <?php if($type == '7') { ?>
                                    <th style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['rejected_by']; ?></th>
                                    <td style="text-align:left">
                                        <a id="clear_invoice_button" href="<?php echo '/businessadmin/clearBusInvoice/'.$bookingsData['response']['Bookings'][$i]['invoice_id']."/7"; ?>">
                                            Approve
                                        </a> 
                                    </td>
                                    <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['invoice_comment_client']; ?></td>
                                    <td style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['invoice_comment_taxivaxi']; ?></td>
                                <?php } ?>
                                <!--<?php if($type == '2') { ?>
                                    <th style="text-align:left"><?php echo $bookingsData['response']['Bookings'][$i]['accepted_by']; ?></th>
                                <?php } ?>-->
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    var type = '<?php echo $this->type; ?>';

    if(type == 1)
    {
        $('#table_booking').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    // {"orderDataType": "dom-text-numeric"},
                    // {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }
    else if(type == 7)
    {
        $('#table_booking').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }
    else if(type == 2)
    {
        $('#table_booking').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    // {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });   
    }
    else
    {
        $('#table_booking').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });
    }

});
</script>
