<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php
    $groupsData = json_decode($this->groups, true);
    // echo $this->groups;
    if(isset($groupsData['response'])){
        $groupsCount = count($groupsData['response']['Groups']);
        $max_budget = floatval($groupsData['response']['Groups'][0]['admin_budget']) - floatval($groupsData['response']['Groups'][0]['admin_allocated']);
    }
    else{
        $groupsCount = 0;
        $max_budget = floatval($groupsData['admin_budget']);
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <!-- <div style="float:left; width:300px; margin-left:500px;">
        <a href="/download/spocs"><button class="btn btn-success btn-block">Download All data as Excel Sheet</button></a>
    </div> -->
    <div style="text-align:center; font-weight:bold; font-size:18px;">Groups</div>
    
    <div style="float:right; width:200px; margin-right:10px;">
        <button class="btn btn-info btn-block" id="add_group_button">ADD New Group</button>
    </div>

    <div class="row" style="padding-top:50px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:15px">
                                <th style="width:30%" class="text-left">Group Name</th>
                                <th style="width:20%" class="text-left">Group Auth  Employee Id</th>
                                <th style="width:20%" class="text-left">Group Auth  Name</th>
                                <th style="width:20%" class="text-left">Group Auth  Email</th>
                                <!-- <th style="width:20%; text-align:center" >BUDGET (Rs)</th>
                                <th style="width:20%; text-align:center" >EXPENSES (Rs)</th> -->
                                <!-- <th style="width:10%; text-align:center" ></th> -->
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$groupsCount; $i++){ ?>
                            <tr style="font-size:13px; cursor:pointer" class="my_row" id="<?php echo $groupsData['response']['Groups'][$i]['group_id'] ?>">
                                <td><?php echo $groupsData['response']['Groups'][$i]['group_name'] ?></td>
                                <td><?php echo $groupsData['response']['Groups'][$i]['group_auth_cid'] ?></td>
                                <td><?php echo $groupsData['response']['Groups'][$i]['group_auth_name'] ?></td>
                                <td><?php echo $groupsData['response']['Groups'][$i]['group_auth_email'] ?></td>
                                <!-- <td style="text-align:center"><?php echo $groupsData['response']['Groups'][$i]['budget'] ?></td>
                                <td style="text-align:center"><?php echo $groupsData['response']['Groups'][$i]['expense'] ?></td> -->
                                <!-- <td class="center">
                                    <?php $l = $groupsData['response']['Groups'][$i]['group_id']; ?>
                                    <a id="delete_group_button" style="display:none" class=" fa-trash" onclick="Confirm.render('Delete this Group?', ' \/group\/delete\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                    </a>
                                </td> -->
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<div id="add_group_form" class="box box-primary" style="width:900px; margin-left:200px">
    <div class="box-header">
        <h3 class="box-title">ADD New Group</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/postAddGroup" method="POST" role="form" id="add_grp_form">
        <div class="box-body">
            <div class="form-group">
                <label for="group_name">Group Name</label>
                <input type="text" class="form-control" name="group_name" id="group_name" placeholder="Group Name" required>
            </div>

            <!-- <label for="budget">Budget</label><br>
            <div class="input-group">
                <span class="input-group-addon">Rs.</span>
                <input type="number" class="form-control" name="budget" id="budget" placeholder="Budget For Group">
            </div>
            <p> (Max Rs.<?php echo $max_budget; ?>)</p> -->

            <label for="budget">Group Approver Employee Id</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="auth_cid" id="auth_cid" placeholder="Employee Id of Approver">
            </div>

            <label for="budget">Group Approver Name</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="auth_name" id="auth_name" placeholder="Name of Approver">
            </div>

            <div class="form-group">
                                <label for="driver_contact">Group Approver Contact No </label><br>
                                <input type="text" class="form-control" value="+91" disabled style="width:7%; float:left;">

                                <input  style="width:90%; float:right;" class="form-control" name="auth_contact" id="auth_contact" placeholder="Contact No" required type="text" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="10">
                            </div><br><br>

            <label for="budget">Group Approver Email</label><br>
            <div class="input-group" style="clear:left;">
                <span class="input-group-addon">@</span>
                <input type="email" class="form-control email" name="auth_email" id="auth_email" placeholder="Email/Username of Approver">
            </div><br>

            <label for="budget">Approver Password</label><br>
            <div class="form-group">
                <input type="password" class="form-control" name="auth_password" id="auth_password" placeholder="Password for Approver Account">
            </div>

            <br><label for="budget">Tour Type</label><br>
            <div class="form-group">
                <?php if($_COOKIE['is_radio'] == '1') {?>
                <label>
                    <div class="icheckbox_minimal-red checked" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_radio" id="is_radio" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Radio
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_local'] == '1') {?>
                <label style="margin-left:45px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_local" id="is_local" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Local Package
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_outstation'] == '1') {?>
                <label style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_outstation" id="is_outstation" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Outstation
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_bus'] == '1') {?>
                <label style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_bus" id="is_bus" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Bus
                </label>
                <?php } ?>
            </div>
        </div><!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="btn btn-primary" style="color:yellow; background-color:black" id="cancel_group_button">Cancel</div>
        </div>
    </form>
</div>

<div id="edit_group_form" class="box box-primary" style="width:900px; margin-left:200px">
    <div class="box-header">
        <h3 class="box-title">Edit Group</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/postEditGroup" method="POST" role="form">
        <input type="hidden" name="edit_group_id" id="edit_group_id">
        <div class="box-body">
            <div class="form-group">
                <label for="group_name">Group Name</label>
                <input type="text" class="form-control" name="edit_group_name" id="edit_group_name" placeholder="Group Name" required>
            </div>

            <!-- <label for="budget">Budget</label><br>
            <div class="input-group">
                <span class="input-group-addon">Rs.</span>
                <input type="number" class="form-control" name="edit_budget" id="edit_budget" placeholder="Budget For Group">
            </div>
            <p id="p_max_budget_edit"> </p> -->

            <label for="budget">Authenticator Name</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="edit_auth_name" id="edit_auth_name" placeholder="Name of Authenticator">
            </div>

            <label for="budget">Group Authenticator Email</label><br>
            <div class="input-group" style="clear:left;">
                <span class="input-group-addon">@</span>
                <input type="email" class="form-control" name="edit_auth_email" id="edit_auth_email" readonly>
            </div><br>

            <label for="budget">Tour Type</label><br>
            <div class="form-group">
                <?php if($_COOKIE['is_radio'] == '1') {?>
                <label>
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="r">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_radio" id="edit_is_radio" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_radio_extra" id="edit_radio_extra" value=''>
                    </div>
                    Radio
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_local'] == '1') {?>
                <label style="margin-left:45px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="l">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_local" id="edit_is_local" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_local_extra" id="edit_local_extra" value=''>
                    </div>
                    Local Package
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_outstation'] == '1') {?>
                <label style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="o">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_outstation" id="edit_is_outstation" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_outstation_extra" id="edit_outstation_extra" value=''>
                    </div>
                    Outstation
                </label>
                <?php } ?>
                <?php if($_COOKIE['is_bus'] == '1') {?>
                <label style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="b">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_bus" id="edit_is_bus" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_bus_extra" id="edit_bus_extra" value=''>
                    </div>
                    Bus
                </label>
                <?php } ?>
            </div>
        </div><!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="btn btn-primary" style="color:yellow; background-color:black" id="cancel_group_button2">Cancel</div>
        </div>
    </form>
</div>

<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'aaSorting' : [],
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

    $('#add_group_form').hide();
    $('#edit_group_form').hide();
    
    var max_budget_j = "<?php echo $max_budget; ?>";
    $('#budget').attr({
        "max" : max_budget_j,
        "min" : 0
    });

    $('a').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#add_group_button').click(function(){
        $('#my_table').hide();
        $('#edit_group_form').hide();

        $('#group_name').val('');
        $('#budget').val();
        $('#auth_name').val();
        $('#auth_email').val();
        $('#auth_password').val();
        $('#is_radio').attr('checked', false);
        $('#is_local').attr('checked', false);
        $('#is_outstation').attr('checked', false);
        $('#is_bus').attr('checked', false);
        $('#add_group_form').show();
    });

    $('#cancel_group_button, #cancel_group_button2').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#r').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_radio_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_radio_extra').val('Yes');
        }
    });

    $('#l').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_local_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_local_extra').val('Yes');
        }
    });

    $('#o').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_outstation_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_outstation_extra').val('Yes');
        }
    });


    $('#b').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_bus_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_bus_extra').val('Yes');
        }
    });

    $('#table_booking').on("click", ".my_row", function(){
        var fun = (function(at, gi){
            jQuery.ajax({
                        url: 'http://taxivaxi.in/business/api/viewGroup',
                        type: 'post',
                        data: {
                            access_token: at,
                            group_id: gi
                        },
                        dataType: 'json',
                        success: function (data) {
                            if(data.success == '0')
                            {
                                alert('No such group found. Please select another');
                            }
                            else
                            {
                                console.log(JSON.stringify(data));
                                $('#edit_group_id').val('');
                                $('#edit_group_name').val('');
                                $('#edit_budget').val('');
                                $('#edit_auth_name').val('');
                                $('#edit_auth_email').val('');
                                
                                $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_radio_extra').val('');
                                $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_local_extra').val('');
                                $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_outstation_extra').val('');
                                $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_bus_extra').val('');
                
                                var Group = data.response.Group;
                                
                                $('#edit_group_id').val(Group.id);
                                $('#edit_group_name').val(Group.group_name);
                                $('#edit_budget').val(Group.budget);
                                //********
                                $('#edit_auth_name').val(Group.auth_name);
                                $('#edit_auth_email').val(Group.auth_email);

                                if(Group.is_radio == '0')
                                {
                                    $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                                    $('#edit_radio_extra').val('');
                                }
                                else
                                {
                                    $('#edit_is_radio').closest('div').attr('aria-checked', true).addClass('checked');
                                    $('#edit_radio_extra').val('Yes');
                                }
                                if(Group.is_local == '0')
                                {
                                    $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                                    $('#edit_local_extra').val('');
                                }
                                else
                                {
                                    $('#edit_is_local').closest('div').attr('aria-checked', true).addClass('checked');
                                    $('#edit_local_extra').val('Yes');
                                }
                                if(Group.is_outstation == '0')
                                {
                                    $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                                    $('#edit_outstation_extra').val('');
                                }
                                else
                                {
                                    $('#edit_is_outstation').closest('div').attr('aria-checked', true).addClass('checked');
                                    $('#edit_outstation_extra').val('Yes');
                                }
                                if(Group.is_bus == '0')
                                {
                                    $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                                    $('#edit_bus_extra').val('');
                                }
                                else
                                {
                                    $('#edit_is_bus').closest('div').attr('aria-checked', true).addClass('checked');
                                    $('#edit_bus_extra').val('Yes');
                                }

                                var edit_budget_cur_val = "<?php echo floatval($groupsData['admin_unallocated']); ?>";
                                var max_budget_edit = parseFloat($('#edit_budget').val()) + parseFloat(edit_budget_cur_val) ;
                                $('#edit_budget').attr({
                                    "max" : max_budget_edit,
                                    "min" : Group.allocated
                                });
                                $('#p_max_budget_edit').text("(Min Rs."+ Group.allocated +"-Max Rs."+max_budget_edit+")");
                            }
                        },
                        error: function(data)
                        {
                        }
                    });
        });

        var gi = parseInt($(this).attr('id'));
        var at = '<?php echo $_COOKIE["access_token_business_admin"]?>' ;

        fun(at, gi);

        setTimeout(function(){
            $('#my_table').hide();
            $('#add_group_form').hide();
            $('#edit_group_form').show(); 
        }, 200);
    });
    
    //For Delete Button
    $('.my_row').mouseover(function(){
        $(this).find('a').show();
    });

    $('.my_row').mouseout(function(){
        $(this).find('a').hide();
    });

    /*$('.email').keyup(function() {
        $('span.error-keyup-7').remove();
        var inputVal = $(this).val();
        var emailReg = /^[a-z0-9]{2,}@tcs\.com$/;
        if(!emailReg.test(inputVal)) {
            $(this).after('<span class="error error-keyup-7">Invalid Email Format.</span>');
        }
    });

    $("#add_grp_form").submit(function() {
        var inputVal = $('#auth_email').val();
        var pattern = /^[a-z0-9]{2,}@tcs\.com$/;
        if (pattern.test(inputVal)) {
            return true;
        } else {
            alert('Not a valid Email (TCS Only!!)');
            return false;
        }

    });*/
    
});
</script>

