<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>
<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $type = $this->type;

    $billsData = json_decode($this->bills, true);

    if(isset($billsData['response'])){
        $billsCount = count($billsData['response']['Bills']);
    }
    else{
        $billsCount = 0;
    }

?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">
        <?php if($type=='1'){echo 'Unpaid-Bills';} elseif($type=='2') echo 'Paid Bills';  ?>
    </div>
    <div style="margin-left:470px; font-weight:bold; font-size:18px;"></div>

    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_bills">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <th style="width:5%">BILL ID</th>
                                <th style="width:10%;" >Bill Date</th>
                                <th style="width:5%;" >Bill Type</th>
                                <th style="width:30%;">Bookings Included</th>
                                <th style="width:5%;" >Bill Amount</th>
                                <th>Pay</th>
                                <?php if($type=='2') {?>
                                <th style="width:10%;" >Payment Date</th>
                                <th style="width:10%;" >Payment Amount</th>
                                <th style="width:15%;" >Payment Mode</th>
                                <th style="width:10%;" >Account No</th>
                                <?php } ?>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$billsCount; $i++){ ?>
                            <tr style="font-size:12px; cursor:pointer" class="my_row" id="<?php echo $billsData['response']['Bills'][$i]['id'] ?>">
                                <td><?php echo $billsData['response']['Bills'][$i]['bill_reference_no']; ?></td>
                                <td style="text-align:left"><?php echo date("d M Y - h:i a", strtotime($billsData['response']['Bills'][$i]['created_at'])); ?></td>
                                <td style="text-align:left">
                                    <?php if($billsData['response']['Bills'][$i]['bill_type'] == '0'){ ?>
                                        Radio
                                    <?php }elseif ($billsData['response']['Bills'][$i]['bill_type'] == '1') { ?>
                                        Local
                                    <?php }elseif($billsData['response']['Bills'][$i]['bill_type'] == '2'){ ?>
                                        Outstation
                                    <?php }else{?>
                                        Bus
                                    <?php }?>
                                </td>
                                <td style="text-align:left">
                                    <?php 
                                    $split_array = explode(",", $billsData['response']['Bills'][$i]['booking_ids']);
                                    for($j=0; $j<count($split_array); $j++)
                                    {
                                        if($billsData['response']['Bills'][$i]['bill_type'] == '3') {
                                            echo "<a href='/businessadmin/viewBusBooking/".$split_array[$j]."'>"."TV".$billsData['response']['Bills'][$i]['corporate_code']."BUS".$split_array[$j].",</a> ";
                                        }
                                        else
                                        {
                                            echo "<a href='/businessadmin/viewBooking/".$split_array[$j]."'>"."TV".$billsData['response']['Bills'][$i]['corporate_code'].$split_array[$j].",</a> ";   
                                        }

                                    }?>
                                </td>
                                <td style="text-align:right">
                                    <?php if($billsData['response']['Bills'][$i]['bill_type'] == '3') { ?>
                                        <a id="viewbill_group_button" style="margin-left:23px;" class=" fa-trash" href="<?php echo '/adminbooking/viewBusBill/'.$billsData['response']['Bills'][$i]['id']; ?>">
                                            <?php echo "Rs.".number_format((float)$billsData['response']['Bills'][$i]['bill_amount'], 2, '.', ''); ?>
                                        </a>
                                    <?php } else { ?>
                                        <a id="viewbill_group_button" style="margin-left:23px;" class=" fa-trash" href="<?php echo '/adminbooking/viewBill/'.$billsData['response']['Bills'][$i]['id']; ?>">
                                            <?php echo "Rs.".number_format((float)$billsData['response']['Bills'][$i]['bill_amount'], 2, '.', ''); ?>
                                        </a>
                                    <?php } ?>

                                </td>
								<td>
									<link rel='stylesheet' type='text/css' href='https://admin.citruspay.com/resources/admin/css/Insta-Buy.css'/><script type='text/javascript' src='https://admin.citruspay.com/resources/admin/js/Insta-Buy.js'></script><form action='https://sandbox.citruspay.com/sslperf/taxivaxi' method='post'>
<input type='hidden' name='productSKU' value='<?php echo $billsData['response']['Bills'][$i]['bill_reference_no']; ?>'>
<input type='hidden' name='productName' value='<?php echo $billsData['response']['Bills'][$i]['bill_reference_no']; ?>'>
<input type='hidden' name='orderAmount' value='<?php echo number_format((float)$billsData['response']['Bills'][$i]['bill_amount'], 2, '.', ''); ?>'>
<input type='hidden' name='' value=''>
<input type='hidden' name='' value=''>
<input type='hidden' name='' value=''>
<input type='hidden' name='secSignature' value='6b867d3905eaef9fe2caf037698f18b361c7cdae' />
<input type='hidden' name='oneClickBuy' value='true'>
<input type='hidden' id='buyNowCitrusLogo' value='https://admin.citruspay.com/resources/admin/images/logo_citrus-med.png'>
<input type='hidden' name='customAttributeNames' value='--'>
<div style='width: 100px; text-align: center;'><input type='image' alt='Buy Now' border='0' src='https://admin.citruspay.com/resources/admin/images/btn_buyNow.png' /><br/><a style='text-decoration: none; color: rgb(153, 153, 153); font-family: Arial,Helvetica,sans-serif; font-size: 13px; padding-top: 10px; line-height: 25px;' href='javascript:;' onclick='citrusInstaBuyWhatsThis();'>What's this?</a></div><div id='citrusInstaBuyOverlayWrapper'></div>
</form>
								</td>
                                <?php if($type=='2') { ?>
                                    <td style="text-align:left"><?php echo date("d M Y", strtotime($billsData['response']['Bills'][$i]['payment_date'])); ?></td>
                                    <td style="text-align:right"><?php echo number_format((float)$billsData['response']['Bills'][$i]['payment_amount'], 2, '.', ''); ?></td>
                                    <td style="text-align:left"><?php echo $billsData['response']['Bills'][$i]['payment_mode'] ?></td>
                                    <td style="text-align:left"><?php echo $billsData['response']['Bills'][$i]['payment_account_no'] ?></td>
                                <?php } ?>
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    var type = '<?php echo $this->type; ?>';
    if(type=='1')
    {
        $('#table_bills').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        });     
    }
    else
    {
        $('#table_bills').DataTable({
            'paging': true,
            'aaSorting' : [],
            "stateSave": true,
            "columns": [
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"},
                    {"orderDataType": "dom-text-numeric"}
                ]
        }); 
    }
});
</script>

