<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php
    $subgroupsData = json_decode($this->subgroups, true);
    // echo $this->subgroups;
    if(isset($subgroupsData['response'])){
        $subgroupsCount = count($subgroupsData['response']['Subgroups']);
    }
    else{
        $subgroupsCount = 0;
    }

    $groupsData = json_decode($this->groups, true);
    $groupsCount;
    if(isset($groupsData['response'])){
        $groupsCount = count($groupsData['response']['Groups']);
    }
    else{
        $groupsCount = 0;
    }
?>

<?php echo $this->mess ;?>

<div id="my_table">
    <!-- <div style="float:left; width:300px; margin-left:500px;">
        <a href="/download/spocs"><button class="btn btn-success btn-block">Download All data as Excel Sheet</button></a>
    </div> -->
    <div style="text-align:center; font-weight:bold; font-size:18px;">Sub Groups</div>
    <div style="float:right; width:200px; margin-right:10px;">
        <button class="btn btn-info btn-block" id="add_group_button">ADD New Subgroup</button>
    </div>

    <div class="row" style="padding-top:50px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:15px">
                                <th style="width:20%" class="text-left">Subgroup Name</th>
                                <th style="width:15%" class="text-left">Group Name</th>
                                <th style="width:20%" class="text-left">Subgroup Auth  Employee Id</th>
                                <th style="width:20%" class="text-left">Subgroup Auth  Name</th>
                                <th style="width:20%" class="text-left">Subgroup Auth  Email</th>
                                <!-- <th style="width:15%; text-align:center" >BUDGET (Rs)</th> -->
                                <!-- <th style="width:20%; text-align:center" >EXPENSES (Rs)</th> -->
                                <!-- <th style="width:5%; text-align:center" ></th> -->
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$subgroupsCount; $i++){ ?>
                            <tr style="font-size:13px; cursor:pointer" class="my_row" id="<?php echo $subgroupsData['response']['Subgroups'][$i]['subgroup_id'] ?>">
                                <td><?php echo $subgroupsData['response']['Subgroups'][$i]['subgroup_name'] ?></td>
                                <td><?php echo $subgroupsData['response']['Subgroups'][$i]['group_name'] ?></td>
                                <td><?php echo $subgroupsData['response']['Subgroups'][$i]['subgroup_auth_cid'] ?></td>
                                <td><?php echo $subgroupsData['response']['Subgroups'][$i]['subgroup_auth_name'] ?></td>
                                <td><?php echo $subgroupsData['response']['Subgroups'][$i]['subgroup_auth_email'] ?></td>
                                <!-- <td style="text-align:center"><?php echo $subgroupsData['response']['Subgroups'][$i]['budget'] ?></td>
                                <td style="text-align:center"><?php echo $subgroupsData['response']['Subgroups'][$i]['expense'] ?></td> -->
                                <!-- <td class="center">
                                    <?php $l = $subgroupsData['response']['Subgroups'][$i]['subgroup_id']; ?>
                                    <a id="delete_group_button" style="display:none" class=" fa-trash" onclick="Confirm.render('Delete this Sub-Group?', ' \/subgroup\/delete\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                    </a>
                                </td> -->
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<div id="add_group_form" class="box box-primary" style="width:900px; margin-left:200px">
    <div class="box-header">
        <h3 class="box-title">ADD New Sub-group</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/postAddSubgroup" method="POST" role="form" id="add_subgrp_form">
        <div class="box-body">
            <div class="form-group">
                <label for="group_name">Sub-group Name</label>
                <input type="text" class="form-control" name="subgroup_name" id="subgroup_name" placeholder="Sub-group Name" required>
            </div>

            <div class="control-group">
                <label class="control-label" for="selectError">Group</label>
                    <div class="controls">
                        <select name="group_id" id="group_id" data-rel="chosen" required>
                            <option selected value="">Select</option>
                            <?php for($x=0; $x<$groupsCount; $x++){ ?>
                            <option value="<?php echo $groupsData['response']['Groups'][$x]['group_id'] ?>"><?php echo $groupsData['response']['Groups'][$x]['group_name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </label>
            </div><br>

            <!-- <label for="budget">Budget</label><br>
            <div class="input-group">
                <span class="input-group-addon">Rs.</span>
                <input type="number" class="form-control" name="budget" id="budget" placeholder="Budget For Sub-group">
            </div>
            <p id="p_max_budget"> </p> -->

            <label for="budget">Approver Employee Id</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="auth_cid" id="auth_cid" placeholder="Employee Id of Approver" required>
            </div>

            <label for="budget">Approver Name</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="auth_name" id="auth_name" placeholder="Name of Approver" required>
            </div>

            <div class="form-group">
                                <label for="driver_contact">Approver Contact No </label><br>
                                <input type="text" class="form-control" value="+91" disabled style="width:7%; float:left;">

                                <input  style="width:90%; float:right;" class="form-control" name="auth_contact" id="auth_contact" placeholder="Contact No" required type="text" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="10">
                            </div><br><br>

            <label for="budget">Approver Email</label><br>
            <div class="input-group" style="clear:left;">
                <span class="input-group-addon">@</span>
                <input type="email" class="form-control email" name="auth_email" id="auth_email" placeholder="Email/Username of Approver">
            </div><br>

            <label for="budget">Approver Password</label><br>
            <div class="form-group">
                <input type="password" class="form-control" name="auth_password" id="auth_password" placeholder="Password for Approver Account">
            </div>

            <br><label for="budget">Tour Type</label><br>
            <div class="form-group">
                <label id="is_radio_div">
                    <div class="icheckbox_minimal-red checked" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_radio" id="is_radio" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Radio
                </label>
                <label id="is_local_div" style="margin-left:45px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_local" id="is_local" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Local Package
                </label>
                <label id="is_outstation_div" style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_outstation" id="is_outstation" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Outstation
                </label>
                <label id="is_bus_div" style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="is_bus" id="is_bus" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                    </div>
                    Bus
                </label>
            </div>
        </div><!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="btn btn-primary" style="color:yellow; background-color:black" id="cancel_group_button">Cancel</div>
        </div>
    </form>
</div>

<div id="edit_group_form" class="box box-primary" style="width:900px; margin-left:200px">
    <div class="box-header">
        <h3 class="box-title">Edit Group</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/postEditSubgroup" method="POST" role="form">
        <input type="hidden" name="edit_subgroup_id" id="edit_subgroup_id">
        <div class="box-body">
            <div class="form-group">
                <label for="group_name">Sub-Group Name</label>
                <input type="text" class="form-control" name="edit_subgroup_name" id="edit_subgroup_name" placeholder="Sub-Group Name" required>
            </div>

            <div class="control-group">
                <label class="control-label" for="edit_group_id">Group</label>
                    <div class="controls">
                        <select name="edit_group_id" id="edit_group_id" data-rel="chosen">
                            <option selected value="">Select</option>
                            <?php for($x=0; $x<$groupsCount; $x++){ ?>
                            <option value="<?php echo $groupsData['response']['Groups'][$x]['group_id'] ?>"><?php echo $groupsData['response']['Groups'][$x]['group_name'] ?></option>
                            <?php } ?>
                        </select>
                    </div>
                </label>
            </div><br>

            <!-- <label for="budget">Budget</label><br>
            <div class="input-group">
                <span class="input-group-addon">Rs.</span>
                <input type="number" class="form-control" name="edit_budget" id="edit_budget" placeholder="Budget For Sub-group">
            </div>
            <p id="p_max_budget_edit"> </p> -->

            <label for="budget">Authenticator Name</label><br>
            <div class="form-group">
                <input type="text" class="form-control" name="edit_auth_name" id="edit_auth_name" placeholder="Name of Authenticator">
            </div>

            <label for="budget">Authenticator Email</label><br>
            <div class="input-group" style="clear:left;">
                <span class="input-group-addon">@</span>
                <input type="email" class="form-control" name="edit_auth_email" id="edit_auth_email" placeholder="Email/Username of Authenticator" readonly>
            </div><br>

            <label for="budget">Tour Type</label><br>
            <div class="form-group">
                <label id="is_radio_div_edit">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="r">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_radio" id="edit_is_radio" value="Yes">
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_radio_extra" id="edit_radio_extra" value=''>
                    </div>
                    Radio
                </label>
                <label id="is_local_div_edit" style="margin-left:40px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="l">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_local" id="edit_is_local" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_local_extra" id="edit_local_extra" value=''>
                    </div>
                    Local Package
                </label>
                <label id="is_outstation_div_edit" style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="o">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_outstation" id="edit_is_outstation" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_outstation_extra" id="edit_outstation_extra" value=''>
                    </div>
                    Outstation
                </label>
                <label id="is_bus_div_edit" style="margin-left:20px">
                    <div class="icheckbox_minimal-red" aria-checked="false" aria-disabled="false" style="position: relative;" id="b">
                        <input type="checkbox" class="minimal-red" style="position: absolute; opacity: 0;" name="edit_is_bus" id="edit_is_bus" value="Yes" >
                        <ins class="iCheck-helper" style="position: absolute; top: 0%; left: 0%; display: block; width: 100%; height: 100%; margin: 0px; padding: 0px; border: 0px; opacity: 0; background: rgb(255, 255, 255);">
                        </ins>
                        <input type="hidden" name="edit_bus_extra" id="edit_bus_extra" value=''>
                    </div>
                    Bus
                </label>
            </div>
        </div><!-- /.box-body -->

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="btn btn-primary" style="color:yellow; background-color:black" id="cancel_group_button2">Cancel</div>
        </div>
    </form>
</div>

<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'aaSorting' : [],
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

    var global_subgroup_id;
    var global_subgroup_group_id;
    var global_subgroup_group_unallocated;
    var global_subgroup_budget;
    var global_subgroup_is_radio;
    var global_subgroup_is_local;
    var global_subgroup_is_outstation;
    var global_subgroup_is_bus;
    var global_subgroup_allocated;

    $('#add_group_form').hide();
    $('#edit_group_form').hide();

    $('a').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#add_group_button').click(function(){
        var gc = parseInt('<?php echo $groupsCount; ?>');
        if(gc > 0){
            $('#my_table').hide();
            $('#edit_group_form').hide();
            $('#is_radio_div').hide();
            $('#is_local_div').hide();
            $('#is_outstation_div').hide();
            $('#is_bus_div').hide();

            $('#group_name').val('');
            $('#budget').val();
            $('#auth_name').val();
            $('#auth_email').val();
            $('#auth_password').val();

            $('#is_radio').attr('checked', false);
            $('#is_local').attr('checked', false);
            $('#is_outstation').attr('checked', false);
            $('#is_bus').attr('checked', false);
            
            $('#add_group_form').show();
        }
        else
        {
            alert('Please add Groups first in order to add subgroups');
        }
    });

    $('#cancel_group_button, #cancel_group_button2').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    //***********
    $('#r').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_radio_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_radio_extra').val('Yes');
        }
    });

    //**********
    $('#l').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_local_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_local_extra').val('Yes');
        }
    });

    //**********
    $('#o').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_outstation_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_outstation_extra').val('Yes');
        }
    });

    //**********
    $('#b').click(function () {
        if($(this).hasClass('checked'))
        {
            $(this).removeClass('checked');
            $('#edit_bus_extra').val('');
        }
        else
        {
            $(this).addClass('checked');
            $('#edit_bus_extra').val('Yes');
        }
    });

    //*********
    $('#table_booking').on("click", ".my_row", function(){
        $('#is_radio_div_edit').hide();
        $('#is_local_div_edit').hide();
        $('#is_outstation_div_edit').hide();
        $('#is_bus_div_edit').hide();

        var fun = (function(at, sgi){
            jQuery.ajax({
                        url: 'http://taxivaxi.in/business/api/viewSubgroup',
                        type: 'post',
                        data: {
                            access_token: at,
                            subgroup_id: sgi
                        },
                        dataType: 'json',
                        success: function (data) {
                            if(data.success == '0')
                            {
                                alert('No such subgroup found. Please select another');
                            }
                            else
                            {
                                $('#edit_subgroup_id').val('');
                                $('#edit_group_name').val('');
                                $('#edit_budget').val('');
                                $('#edit_auth_name').val('');
                                $('#edit_auth_email').val('');
                                
                                $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_radio_extra').val('');
                                $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_local_extra').val('');
                                $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_outstation_extra').val('');
                                $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_bus_extra').val('');
                
                                var Subgroup = data.response.Subgroup;

                                global_subgroup_group_id = Subgroup.group_id;
                                global_subgroup_group_unallocated = Subgroup.group_unallocated;
                                global_subgroup_budget = Subgroup.budget;
                                global_subgroup_is_radio = Subgroup.is_radio;
                                global_subgroup_is_local = Subgroup.is_local;
                                global_subgroup_is_outstation = Subgroup.is_outstation;
                                global_subgroup_is_bus = Subgroup.is_bus;
                                global_subgroup_allocated = Subgroup.allocated;
                                
                                $('#edit_subgroup_id').val(Subgroup.id);
                                $('#edit_subgroup_name').val(Subgroup.subgroup_name);
                                $('#edit_budget').val(Subgroup.budget);
                                $('#edit_auth_name').val(Subgroup.auth_name);
                                $('#edit_auth_email').val(Subgroup.auth_email);

                                $("#edit_group_id option").each(function()
                                {
                                    // Add $(this).val() to your list
                                    if($(this).val() == Subgroup.group_id)
                                    {
                                        $(this).attr('selected', true);
                                    }
                                });

                                if(Subgroup.group_is_radio == '1')
                                {
                                    if(Subgroup.is_radio == '0')
                                    {
                                        $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                                        $('#edit_radio_extra').val('');
                                    }
                                    else
                                    {
                                        $('#edit_is_radio').closest('div').attr('aria-checked', true).addClass('checked');
                                        $('#edit_radio_extra').val('Yes');
                                    }
                                    $('#is_radio_div_edit').show();
                                }
                                
                                if(Subgroup.group_is_local == '1')
                                {
                                    if(Subgroup.is_local == '0')
                                    {
                                        $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                                        $('#edit_local_extra').val('');
                                    }
                                    else
                                    {
                                        $('#edit_is_local').closest('div').attr('aria-checked', true).addClass('checked');
                                        $('#edit_local_extra').val('Yes');
                                    }
                                    $('#is_local_div_edit').show();
                                }

                                if(Subgroup.group_is_outstation == '1')
                                {
                                    if(Subgroup.is_outstation == '0')
                                    {
                                        $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                                        $('#edit_outstation_extra').val('');
                                    }
                                    else
                                    {
                                        $('#edit_is_outstation').closest('div').attr('aria-checked', true).addClass('checked');
                                        $('#edit_outstation_extra').val('Yes');
                                    }
                                    $('#is_outstation_div_edit').show();
                                }

                                if(Subgroup.group_is_bus == '1')
                                {
                                    if(Subgroup.is_bus == '0')
                                    {
                                        $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                                        $('#edit_bus_extra').val('');
                                    }
                                    else
                                    {
                                        $('#edit_is_bus').closest('div').attr('aria-checked', true).addClass('checked');
                                        $('#edit_bus_extra').val('Yes');
                                    }
                                    $('#is_bus_div_edit').show();
                                }

                                $('#p_max_budget_edit').text("(Min Rs."+ global_subgroup_allocated +"-Max Rs." + parseFloat(parseFloat(global_subgroup_budget) + parseFloat(global_subgroup_group_unallocated)) + ")");
                                $('#edit_budget').attr({
                                    "max" :  parseFloat(parseFloat(global_subgroup_budget) + parseFloat(global_subgroup_group_unallocated)),
                                    "min" : global_subgroup_allocated
                                });
                            }
                        },
                        error: function(data)
                        {
                        }
                    });
        });

        var sgi = parseInt($(this).attr('id'));
        global_subgroup_id = sgi;
        var at = '<?php echo $_COOKIE["access_token_business_admin"]?>' ;

        fun(at, sgi);
        $('#my_table').hide();
        $('#add_group_form').hide();
        $('#edit_group_form').show(); 
    });
    
    //For Delete Button
    $('.my_row').mouseover(function(){
        $(this).find('a').show();
    });

    $('.my_row').mouseout(function(){
        $(this).find('a').hide();
    });

    //For Add form
    $("#group_id").change(function(){
        $('#is_radio_div').hide();
        $('#is_local_div').hide();
        $('#is_outstation_div').hide();
        $('#is_bus_div').hide();

        var gi = $(this).val();
        var at = '<?php echo $_COOKIE["access_token_business_admin"] ?>';
        jQuery.ajax({
            url: 'http://taxivaxi.in/business/api/viewGroup',
            type: 'post',
            data: {
                access_token: at,
                group_id: gi
            },
            dataType: 'json',
            success: function (data) {
                if(data.success == '0')
                    alert('No such group found. Please select another');
                else
                {
                    var Group = data.response.Group;
                    $('#p_max_budget').text("(Max Rs." + parseFloat(Group.unallocated) + ")");
                    $('#budget').attr({
                        "max" : parseInt(Group.unallocated),
                        "min" : 0
                    });

                    if(Group.is_radio == '1')
                    {
                        $('#is_radio_div').show();
                    }

                    if(Group.is_local == '1')
                    {
                        $('#is_local_div').show();
                    }

                    if(Group.is_outstation == '1')
                    {
                        $('#is_outstation_div').show();
                    }

                    if(Group.is_bus == '1')
                    {
                        $('#is_bus_div').show();
                    }

                }
            },
            error: function(data)
            {
            }
        });
    });
    
    $('#edit_group_id').change(function(){
        $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
        $('#edit_radio_extra').val('');
        $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
        $('#edit_local_extra').val('');
        $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
        $('#edit_outstation_extra').val('');
        $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
        $('#edit_bus_extra').val('');

        $('#is_radio_div_edit').hide();
        $('#is_local_div_edit').hide();
        $('#is_outstation_div_edit').hide();
        $('#is_bus_div_edit').hide();

        var gi = $('#edit_group_id').val();
        // alert(global_subgroup_id + "-" + global_subgroup_group_id + "-" + global_subgroup_group_unallocated);
        var at = '<?php echo $_COOKIE["access_token_business_admin"] ?>';
        jQuery.ajax({
            url: 'http://taxivaxi.in/business/api/viewGroup',
            type: 'post',
            data: {
                access_token: at,
                group_id: gi
            },
            dataType: 'json',
            success: function (data) {
                if(data.success == '0')
                    alert('No such group found. Please select another');
                else
                {
                    var Group = data.response.Group;

                    if(Group.id == global_subgroup_group_id)
                    {
                        $('#p_max_budget_edit').text("(Min Rs."+ global_subgroup_allocated +"-Max Rs." + parseFloat(parseFloat(global_subgroup_budget) + parseFloat(global_subgroup_group_unallocated)) + ")");

                        $('#edit_budget').attr({
                            "max" :  parseFloat(parseFloat(global_subgroup_budget) + parseFloat(global_subgroup_group_unallocated)),
                            "min" : global_subgroup_allocated
                        });

                        if(Group.is_radio == '1')
                        {
                            if(global_subgroup_is_radio == '0')
                            {
                                $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_radio_extra').val('');
                            }
                            else
                            {
                                $('#edit_is_radio').closest('div').attr('aria-checked', true).addClass('checked');
                                $('#edit_radio_extra').val('Yes');
                            }
                            $('#is_radio_div_edit').show();
                        }
                        
                        if(Group.is_local == '1')
                        {
                            if(global_subgroup_is_local == '0')
                            {
                                $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_local_extra').val('');
                            }
                            else
                            {
                                $('#edit_is_local').closest('div').attr('aria-checked', true).addClass('checked');
                                $('#edit_local_extra').val('Yes');
                            }
                            $('#is_local_div_edit').show();
                        }

                        if(Group.is_outstation == '1')
                        {
                            if(global_subgroup_is_outstation == '0')
                            {
                                $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_outstation_extra').val('');
                            }
                            else
                            {
                                $('#edit_is_outstation').closest('div').attr('aria-checked', true).addClass('checked');
                                $('#edit_outstation_extra').val('Yes');
                            }
                            $('#is_outstation_div_edit').show();
                        }

                        if(Group.is_bus == '1')
                        {
                            if(global_subgroup_is_bus == '0')
                            {
                                $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                                $('#edit_bus_extra').val('');
                            }
                            else
                            {
                                $('#edit_is_bus').closest('div').attr('aria-checked', true).addClass('checked');
                                $('#edit_bus_extra').val('Yes');
                            }
                            $('#is_bus_div_edit').show();
                        }
                    }
                    else
                    {
                        $('#p_max_budget_edit').text("(Min Rs."+ global_subgroup_allocated +"-Max Rs." + parseFloat(Group.unallocated) + ")");
                        $('#edit_budget').attr({
                            "max" : parseFloat(Group.unallocated),
                            "min" : global_subgroup_allocated
                        });

                        if(Group.is_radio == '1')
                        {
                            $('#edit_is_radio').closest('div').attr('aria-checked', false).removeClass('checked');
                            $('#edit_radio_extra').val('');
                            $('#is_radio_div_edit').show();
                        }

                        if(Group.is_local == '1')
                        {
                            $('#edit_is_local').closest('div').attr('aria-checked', false).removeClass('checked');
                            $('#edit_local_extra').val('');
                            $('#is_local_div_edit').show();
                        }
                                
                        if(Group.is_outstation == '1')
                        {
                            $('#edit_is_outstation').closest('div').attr('aria-checked', false).removeClass('checked');
                            $('#edit_outstation_extra').val('');
                            $('#is_outstation_div_edit').show();
                        }

                        if(Group.is_bus == '1')
                        {
                            $('#edit_is_bus').closest('div').attr('aria-checked', false).removeClass('checked');
                            $('#edit_bus_extra').val('');
                            $('#is_bus_div_edit').show();
                        }
                    }
                }
            },
            error: function(data)
            {
            }
        });
    });

    /*$('.email').keyup(function() {
        $('span.error-keyup-7').remove();
        var inputVal = $(this).val();
        var emailReg = /^[a-z0-9]{2,}@tcs\.com$/;
        if(!emailReg.test(inputVal)) {
            $(this).after('<span class="error error-keyup-7">Invalid Email Format.</span>');
        }
    });

    $("#add_subgrp_form").submit(function() {
        var inputVal = $('#auth_email').val();
        var pattern = /^[a-z0-9]{2,}@tcs\.com$/;
        if (pattern.test(inputVal)) {
            return true;
        } else {
            alert('Not a valid Email (TCS Only!!)');
            return false;
        }

    });*/
    
});
</script>