<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php
    $codeData = json_decode($this->ass_codes, true);
    if(isset($codeData['response'])){
        $codeCount = count($codeData['response']['AssCodes']);
    }
    else{
        $codeCount = 0;
    }
?>

<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">Assessment Codes</div>
    <div style="float:right; width:200px; margin-right:10px;">
        <button class="btn btn-info btn-block" id="add_group_button">ADD Assessment Code</button>
    </div>

    <div class="row" style="padding-top:50px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:12px">
                                <th class="text-left">ID</th>
                                <th class="text-left">CODE</th>
                                <th style="width:40%" class="text-left">DESCRIPTION</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$codeCount; $i++){ ?>
                            <tr style="font-size:12px; cursor:pointer" class="my_row" id="<?php echo $codeData['response']['AssCodes'][$i]['id'] ?>">
                                <td><?php echo $codeData['response']['AssCodes'][$i]['id'] ?></td>
                                <td><?php echo $codeData['response']['AssCodes'][$i]['assessment_code'] ?></td>
                                <td><?php echo $codeData['response']['AssCodes'][$i]['code_desc'] ?></td>
                              
                                <td class="center">
                                    <?php $l = $codeData['response']['AssCodes'][$i]['id']; ?>
                                   <!-- <a id="delete_group_button" style="display:none" class=" fa-trash" onclick="Confirm.render('Delete this Employee?', ' \/assessment_code\/delete\/<?php echo $l ?> ');">
                                        <i class="glyphicon glyphicon-trash icon-white"></i>
                                    </a>-->
                                </td> 
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<div id="add_group_form" class="box box-primary" style="width:900px; margin-left:200px">
    <div class="box-header">
        <h3 class="box-title">ADD Assessment Code</h3>
    </div><!-- /.box-header -->
    <!-- form start -->
    <form action="/postAddAssessmentCode" method="POST" role="form" id="add_assessment_code_form">
        <div class="box-body">

            <div class="form-group">
                <label for="group_name">Assessment Code</label>
                <input type="text" class="form-control" name="assessment_code" id="assessment_code" placeholder="Assessment Code" required>
            </div>

            <div class="form-group">
                <label for="group_name">Code Description</label>
                <input type="text" class="form-control" name="code_desc" id="code_desc" placeholder="Dscription of Code" required>
            </div>

        <div class="box-footer">
            <button type="submit" class="btn btn-primary">Submit</button>
            <div class="btn btn-warning" id="cancel_group_button">Cancel</div>
        </div>
    </form>
</div>

<div id="try_group_form"></div>



<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'sort' : false,
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

    var global_people_id;
    var global_people_user_id;

    $('#add_group_form').hide();
    $('#edit_group_form').hide();

    $('a').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    $('#add_group_button').click(function(){
       // var sp = parseInt('<?php echo $codeCount; ?>');
        
        
            $('#my_table').hide();
            $('#edit_group_form').hide();

            $('#add_group_form').show();
        
   
    });

    $('#cancel_group_button, #cancel_group_button2').click(function(){
        $('#my_table').show();
        $('#add_group_form').hide();
        $('#edit_group_form').hide();
    });

    //*********
    //edit
    /*$('.my_row').click(function(){

        var fun = (function(at, pi){
            jQuery.ajax({
                        url: 'http://business.tv/viewPeople',
                        type: 'post',
                        data: {
                            access_token: at,
                            people_id: pi
                        },
                        dataType: 'json',
                        success: function (data) {
                            if(data.success == '0')
                            {
                                alert('No such Employee found. Please select another');
                            }
                            else
                            {
                                $('#edit_people_id').val('');
                                $('#edit_people_cid').val('');
                                $('#edit_people_name').val('');
                                $('#edit_people_email').val('');
                                $('#edit_people_contact').val('');
                
                                var People = data.response.People;

                                global_spoc_user_id = People.user_id;
                                
                                $('#edit_people_id').val(People.id);
                                $('#edit_people_cid').val(People.people_cid);
                                $('#edit_people_name').val(People.people_name);
                                $('#edit_people_contact').val(People.people_contact);
                                $('#edit_people_email').val(People.people_email);

                                $("#edit_user_id option").each(function()
                                {
                                    // Add $(this).val() to your list
                                    if($(this).val() == People.user_id)
                                    {
                                        $(this).attr('selected', true);
                                    }
                                });
                            }
                        },
                        error: function(data)
                        {
                        }
                    });
        });

        var pi = parseInt($(this).attr('id'));
        global_people_id = pi;
        var at = '<?php echo $_COOKIE["access_token_business_admin"]?>' ;

        fun(at, pi);
        $('#my_table').show();
        // $('#add_group_form').hide();
        // $('#edit_group_form').show(); 
    });*/
    
    //For Delete Button
    $('.my_row').mouseover(function(){
        $(this).find('a').show();
    });

    $('.my_row').mouseout(function(){
        $(this).find('a').hide();
    });

    /*$('.email_check').keyup(function() {
        $('span.error-keyup-7').remove();
        var inputVal = $(this).val();
        var emailReg = /^[a-z0-9]{2,}@tcs\.com$/;
        if(!emailReg.test(inputVal)) {
            $(this).after('<span class="error error-keyup-7">Invalid Email Format.</span>');
        }
    });

    $("#add_employee_form").submit(function() {
        var inputVal = $('#people_email').val();
        var pattern = /^[a-z0-9]{2,}@tcs\.com$/;
        if (pattern.test(inputVal)) {
            return true;
        } else {
            alert('Not a valid Email (TCS Only!!)');
            return false;
        }

    });*/

    
});
</script>