<?php if(isset($_COOKIE['success'])) { ?>
    <div class="alert alert-success alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['success'] ?>
    </div>
<?php } ?>

<?php if(isset($_COOKIE['fail'])) { ?>
    <div class="alert alert-danger alert-dismissable">
        <i class="fa fa-check"></i>
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <?php echo $_COOKIE['fail'] ?>
    </div>
<?php } ?>

<?php
    $ratesData = json_decode($this->rates, true);
    // var_dump($ratesData);
    if(isset($ratesData['response'])){
        $ratesCount = count($ratesData['response']['Rates']);
    }
    else{
        $ratesCount = 0;
    }
?>
<?php echo $this->mess ;?>

<div id="my_table">
    <div style="text-align:center; font-weight:bold; font-size:18px;">Rates</div>
	<br>
    <div class="row" style="padding-top:30px">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    <h3 class="box-title"></h3>
                    
                </div><!-- /.box-header -->
                <div class="box-body table-responsive no-padding">
                    <table class="table table-striped table-bordered datatable" id="table_booking">
                        <thead>
                            <tr style="width:100%; font-size:11px">
                                <th style="text-align:left" >Package Name</th>
                                <th style="text-align:left" >City</th>
                                <th style="text-align:left" >Taxi Type</th>
                                <th style="text-align:left" >Tour Type</th>
                                <th style="text-align:left" >Kms Included</th>
                                <th style="text-align:left" >Hours Included</th>
                                <th style="text-align:left" >Extra Rate/Km(Rs.)</th>
                                <th style="text-align:left" >Extra Rate/Hr(Rs.)</th>
                                <th style="text-align:left" >Base Rate(Rs.)</th>
                                <th style="text-align:left" >Night Rate(Rs.)</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php for($i=0; $i<$ratesCount; $i++){?>
                            <tr style="font-size:11px;" class="my_row" >

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['package_name'] ?></td>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['city_name'] ?></td>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['taxi_type'] ?></td>

                                <td style="text-align:left">
                                    <?php if($ratesData['response']['Rates'][$i]['tour_type'] == '1'){ ?>
                                        Local
                                    <?php }else{ ?>
                                        Outstation
                                    <?php }?>
                                </td>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['kms'] ?></td>

                                <?php if($ratesData['response']['Rates'][$i]['tour_type'] == '1'){ ?>
                                    <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['hours']." hrs" ?></td>
                                <?php }else{ ?>
                                    <td style="text-align:left">-</td>
                                <?php }?>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['km_rate'] ?></td>

                                <?php if($ratesData['response']['Rates'][$i]['tour_type'] == '1'){ ?>
                                    <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['hour_rate'] ?></td>
                                <?php }else{ ?>
                                    <td style="text-align:left">-</td>
                                <?php }?>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['base_rate'] ?></td>

                                <td style="text-align:left"><?php echo $ratesData['response']['Rates'][$i]['night_rate'] ?></td>

                                
                            </tr>
                            <?php } ?>
                        </tbody>
                    </table>
                </div><!-- /.box-body -->
            </div><!-- /.box -->
        </div>
    </div>
</div>

<script>
$(document).ready(function() {

    $('#table_booking').DataTable({
        'paging': true,
        'sort': false,
        "stateSave": true,
        "columns": [
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"},
                {"orderDataType": "dom-text-numeric"}
            ]
    });

    
});
</script>

