<?php
$invoiceData = json_decode($this->invoice, true);
?>

<style>
div.img {
    margin: 5px;
    border: 1px solid #ccc;
    float: left;
    width: 180px;
}

div.img:hover {
    border: 1px solid #777;
}

div.img img {
    width: 100%;
    height: auto;
}

div.desc {
    padding: 15px;
    text-align: center;
}
</style>

<?php if($invoiceData['response']['Invoice']['duty_slip'] != ''  ) {?>
    <div class="img" style="margin-left:630px">
        <a target="_blank" href="<?php echo $invoiceData['response']['Invoice']['duty_slip'] ; ?>">
            <img src="<?php echo $invoiceData['response']['Invoice']['duty_slip'] ; ?>">
        </a>
        <div class="desc">Payin-Slip</div>
    </div>
<?php } ?>

<div class="row">
    <div class="box col-md-12">
    <!-- <div class="box-inner"> -->
    <!-- <div class="box-header well" data-original-title=""> -->
        <h2 style="margin-left:580px"><i class="glyphicon glyphicon-list-alt"></i> Invoice : <a href="/businessadmin/viewBooking/<?php echo $invoiceData['response']['Invoice']['booking_id'] ?>"> <?php echo $invoiceData['response']['Invoice']['reference_no']; ?></a></h2>
    <!-- </div> -->

	<table class="table table-striped table-bordered bootstrap-datatable datatable responsive" style="width:700px; margin-left:370px">

	<tr>
        <th>Car Model</th>
        <td><?php echo $invoiceData['response']['Invoice']['taxi_model_name']; ?></td>
    </tr>

    <tr>
        <th>Package Name</th>
        <td><?php echo $invoiceData['response']['Invoice']['rate_name']; ?></td>
    </tr>

    <tr>
        <th>Pickup Date</th>
        <td><?php echo date("d M Y", strtotime($invoiceData['response']['Invoice']['pickup_date'])); ?></td>
    </tr>

    <tr>
        <th>Pickup Time</th>
        <td><?php echo date("h:i a", strtotime($invoiceData['response']['Invoice']['pickup_time'])); ?></td>
    </tr>

    <tr>
        <th>Drop Date</th>
        <td><?php echo date("d M Y", strtotime($invoiceData['response']['Invoice']['drop_date'])); ?></td>
    </tr>

    <tr>
        <th>Drop Time</th>
        <td><?php echo date("h:i a", strtotime($invoiceData['response']['Invoice']['drop_time'])); ?></td>
    </tr>

    <?php if($invoiceData['response']['Invoice']['tour_type'] == 'Local') { ?>
    <tr>
        <th>Total Hours Done</th>
        <td><?php echo $invoiceData['response']['Invoice']['hours_done']; ?></td>
    </tr>
    <?php } else { ?>
    <tr>
        <th>No of days</th>
        <td><?php echo $invoiceData['response']['Invoice']['hours_done']; ?></td>
    </tr>
    <?php } ?>

    <?php if($invoiceData['response']['Invoice']['tour_type'] == 'Local') { ?>
     <tr>
        <th>Allowed Hours</th>
        <td><?php echo $invoiceData['response']['Invoice']['allowed_hrs']; ?></td>
    </tr>
    <tr>
        <th>Extra Hours</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_hours']; ?></td>
    </tr>

    <tr style="border: solid 2px #ff0000">
        <th>Extra Hours Charge (@Rs<?php echo $invoiceData['response']['Invoice']['hour_rate'] ?>/Hour)</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_hours_charge']; ?></td>
    </tr>
    <?php } ?>

    <tr>
        <th>Starting Km</th>
        <td><?php echo $invoiceData['response']['Invoice']['start_km']; ?></td>
    </tr>

    <tr>
        <th>Ending Km</th>
        <td><?php echo $invoiceData['response']['Invoice']['end_km']; ?></td>
    </tr>

    <tr>
        <th>Total Kms Done</th>
        <td><?php echo $invoiceData['response']['Invoice']['kms_done']; ?></td>
    </tr>
     <tr>
        <th>Allowed Kms</th>
        <td><?php echo $invoiceData['response']['Invoice']['allowed_kms']; ?></td>
    </tr>
    <tr>
        <th>Extra Kms</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_kms']; ?></td>
    </tr>

    <tr style="border-top: solid 2px #ff0000; border-left: solid 2px #ff0000; border-right: solid 2px #ff0000">
        <th>Extra Kms Charge (@Rs<?php echo $invoiceData['response']['Invoice']['km_rate'] ?>/Km)</th>
        <td><?php echo $invoiceData['response']['Invoice']['extra_kms_charge']; ?></td>
    </tr>

    <tr style="border-left: solid 2px #ff0000; border-right: solid 2px #ff0000;">
        <th>Package Base Rate</th>
        <td><?php echo $invoiceData['response']['Invoice']['base_rate']; ?></td>
    </tr>

    <tr style="border-bottom: solid 2px #ff0000; border-left: solid 2px #ff0000; border-right: solid 2px #ff0000">
        <th>Diver Charges</th>
        <td><?php echo $invoiceData['response']['Invoice']['driver']; ?></td>
    </tr>

    <tr>
        <th>Total (Excluding Tax)</th>
        <td><?php echo $invoiceData['response']['Invoice']['total_ex_tax']; ?></td>
    </tr>

    <tr style="border-top: solid 2px #ff0000; border-left: solid 2px #ff0000; border-right: solid 2px #ff0000">
        <th>Tax (@<?php echo $invoiceData['response']['Invoice']['tax_rate']; ?>%)</th>
        <td><?php echo $invoiceData['response']['Invoice']['tax']; ?></td>
    </tr>

    <tr style="border-left: solid 2px #ff0000; border-right: solid 2px #ff0000">
        <th>Others (Parking, Toll Tax etc.)</th>
        <td><?php echo $invoiceData['response']['Invoice']['extras']; ?></td>
    </tr>

    <tr style="border-left: solid 2px #ff0000; border-right: solid 2px #ff0000">
        <th>Management Fee (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_rate'] ?>)</th>
        <td><?php echo "Rs. ".$invoiceData['response']['Invoice']['taxivaxi_charge']; ?></td>
    </tr>

    <tr style="border-left: solid 2px #ff0000; border-right: solid 2px #ff0000; border-bottom: solid 2px #ff0000;">
        <th>Service Tax (@<?php echo $invoiceData['response']['Invoice']['taxivaxi_tax_rate'] ?>%)</th>
        <td><?php echo "Rs. ".$invoiceData['response']['Invoice']['taxivaxi_tax_charge']; ?></td>
    </tr>
    <tr>
        <th>&nbsp;</th>
        <td>&nbsp;</td>
    </tr>
    <tr bgcolor="#1fc516">
        <th>Total (Rs)</th>
        <td><?php echo number_format((float)$invoiceData['response']['Invoice']['sub_total'], 2, '.', ''); ?></td>
    </tr>

   
    </table>
    </div>
    </div>
    </div>
    <!--/span-->

    </div><!--/row-->

    <?php if($invoiceData['response']['Invoice']['status'] == '1') { ?>
    <div class="row">
    <div class="box col-md-12">
        <h3>Approve / Reject Invoice</h3>
    <table class="table table-striped table-bordered bootstrap-datatable datatable responsive" style="width:700px; margin-left:370px">
    <tr>
        <th>Approve</th>
        <td>
            <a href="<?php echo '/businessadmin/clearInvoice/'.$invoiceData['response']['Invoice']['id']."/1"; ?>">
            Approve
            </a> 
        </td>
    </tr>

    <tr>
        <th>Reject/Comment for Taxivaxi</th>
        <td>
            <form action="/businessadmin/commentInvoice" method="POST">
                <input type="hidden" value="<?php echo $invoiceData['response']['Invoice']['id'] ?>" name="invoice_id">
                <textarea rows="4" cols="50" name="comment"></textarea>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
        </td>
    </tr>
    </table>
    </div>
    </div>
    </div>
    <!--/span-->
    </div><!--/row-->
    <?php } ?>
